<!DOCTYPE html>

<html lang="zh-Hans" xml:lang="zh-Hans" xmlns="http://www.w3.org/1999/xhtml"><head>
<meta charset="utf-8"/>
<meta content="quarto-1.10.18" name="generator"/>
<meta content="width=device-width, initial-scale=1.0, user-scalable=yes" name="viewport"/>
<title>四大事务所效应 – 会计研究项目报告</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>
<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta content="./" name="quarto:offset"/>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet"/>
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" id="quarto-text-highlighting-styles" rel="stylesheet"/>
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet"/>
<link append-hash="true" data-mode="light" href="site_libs/bootstrap/bootstrap-261e60fdf64a0e003ec2340fd2db30d7.min.css" id="quarto-bootstrap" rel="stylesheet"/>
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "没有结果",
    "search-matching-documents-text": "匹配的文档",
    "search-copy-link-title": "复制搜索链接",
    "search-hide-matches-text": "隐藏其它匹配结果",
    "search-more-match-text": "更多匹配结果",
    "search-more-matches-text": "更多匹配结果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "提交",
    "search-label": "搜索"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
<script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>
<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<link href="styles.css" rel="stylesheet"/>
<link href="empirical.css" rel="stylesheet"/>
</head>
<body class="nav-sidebar docked empirical-report quarto-light">
<div id="quarto-search-results"></div>
<header class="headroom fixed-top" id="quarto-header">
<nav class="quarto-secondary-nav">
<div class="container-fluid d-flex">
<button aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" class="quarto-btn-toggle btn" data-bs-target=".quarto-sidebar-collapse-item" data-bs-toggle="collapse" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }" role="button" type="button">
<i class="bi bi-layout-text-sidebar-reverse"></i>
</button>
<nav aria-label="breadcrumb" class="quarto-page-breadcrumbs"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./23_big4_effect.html">四大事务所效应</a></li></ol></nav>
<a aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" class="flex-grow-1" data-bs-target=".quarto-sidebar-collapse-item" data-bs-toggle="collapse" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }" role="navigation">
</a>
<button aria-label="搜索" class="btn quarto-search-button" onclick="window.quartoOpenSearch();" type="button">
<i class="bi bi-search"></i>
</button>
</div>
</nav>
</header>
<!-- content -->
<div class="quarto-container page-columns page-rows-contents page-layout-article" id="quarto-content">
<!-- sidebar -->
<nav class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto" id="quarto-sidebar">
<div class="pt-lg-2 mt-2 text-left sidebar-header">
<div class="sidebar-title mb-0 py-0">
<a href="./">会计研究项目报告</a>
</div>
</div>
<div class="mt-2 flex-shrink-0 align-items-center">
<div class="sidebar-search">
<div class="" id="quarto-search" title="搜索"></div>
</div>
</div>
<div class="sidebar-menu-container">
<ul class="list-unstyled mt-1">
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./01_core_summary.html">
<span class="menu-text">核心摘要</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./02_core_results.html">
<span class="menu-text">核心结果</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./03_background.html">
<span class="menu-text">背景</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./21_adoption.html">
<span class="menu-text">四大审计师的采用</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./22_diffusion.html">
<span class="menu-text">企业网络传导</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link active" href="./23_big4_effect.html">
<span class="menu-text">四大事务所效应</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./24_auditor_quality.html">
<span class="menu-text">审计师效应</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./25_matching.html">
<span class="menu-text">客户、事务所和审计师的匹配</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./26_akm.html">
<span class="menu-text">AKM</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./31_biweekly_memo.html">
<span class="menu-text">双周备忘录</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./32_active_tasks.html">
<span class="menu-text">当前任务</span></a>
</div>
</li>
<li class="sidebar-item">
<div class="sidebar-item-container">
<a class="sidebar-item-text sidebar-link" href="./33_data_pipeline.html">
<span class="menu-text">数据流程</span></a>
</div>
</li>
</ul>
</div>
</nav>
<div class="quarto-sidebar-collapse-item" data-bs-target=".quarto-sidebar-collapse-item" data-bs-toggle="collapse" id="quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
<div class="sidebar margin-sidebar" id="quarto-margin-sidebar">
<nav class="toc-active" id="TOC" role="doc-toc">
<h2 id="toc-title">该页面内容</h2>
<ul>
<li><a class="nav-link active" data-scroll-target="#概述" href="#概述" id="toc-概述">概述</a></li>
<li><a class="nav-link" data-scroll-target="#核心结果" href="#核心结果" id="toc-核心结果">核心结果</a></li>
<li><a class="nav-link" data-scroll-target="#literature-feasible-baseline" href="#literature-feasible-baseline" id="toc-literature-feasible-baseline">1. 文献中现有数据可行的基础做法</a>
<ul class="collapse">
<li><a class="nav-link" data-scroll-target="#客户特征匹配与失败指标" href="#客户特征匹配与失败指标" id="toc-客户特征匹配与失败指标">1.1 客户特征、匹配与失败指标</a></li>
<li><a class="nav-link" data-scroll-target="#长期风险与事务所客户选择" href="#长期风险与事务所客户选择" id="toc-长期风险与事务所客户选择">1.2 长期风险与事务所客户选择</a></li>
<li><a class="nav-link" data-scroll-target="#中国审计前质量审计调整与制度环境" href="#中国审计前质量审计调整与制度环境" id="toc-中国审计前质量审计调整与制度环境">1.3 中国：审计前质量、审计调整与制度环境</a></li>
<li><a class="nav-link" data-scroll-target="#中国竞争所有权与监管背景" href="#中国竞争所有权与监管背景" id="toc-中国竞争所有权与监管背景">1.4 中国：竞争、所有权与监管背景</a></li>
<li><a class="nav-link" data-scroll-target="#组织变化与同一客户的处理比较" href="#组织变化与同一客户的处理比较" id="toc-组织变化与同一客户的处理比较">1.5 组织变化与同一客户的处理比较</a></li>
<li><a class="nav-link" data-scroll-target="#选择模型与工具变量的适用条件" href="#选择模型与工具变量的适用条件" id="toc-选择模型与工具变量的适用条件">1.6 选择模型与工具变量的适用条件</a></li>
<li><a class="nav-link" data-scroll-target="#连续盈利消息与市场反应" href="#连续盈利消息与市场反应" id="toc-连续盈利消息与市场反应">1.7 连续盈利消息与市场反应</a></li>
<li><a class="nav-link" data-scroll-target="#分析师预测与公告前后信息环境" href="#分析师预测与公告前后信息环境" id="toc-分析师预测与公告前后信息环境">1.8 分析师预测与公告前后信息环境</a></li>
</ul></li>
<li><a class="nav-link" data-scroll-target="#客户选择与审计意见四大如何形成较低风险的客户组合" href="#客户选择与审计意见四大如何形成较低风险的客户组合" id="toc-客户选择与审计意见四大如何形成较低风险的客户组合">2. 客户事前差异与可观察选择</a>
<ul class="collapse">
<li><a class="nav-link" data-scroll-target="#进入前客户特征" href="#进入前客户特征" id="toc-进入前客户特征">2.1 进入前客户特征</a></li>
<li><a class="nav-link" data-scroll-target="#年度客户匹配可观察调整后仍有质量差异" href="#年度客户匹配可观察调整后仍有质量差异" id="toc-年度客户匹配可观察调整后仍有质量差异">2.2 年度客户匹配：可观察调整后仍有质量差异</a></li>
<li><a class="nav-link" data-scroll-target="#客户进入留任与退出" href="#客户进入留任与退出" id="toc-客户进入留任与退出">2.3 客户进入、留任与退出</a></li>
</ul></li>
<li><a class="nav-link" data-scroll-target="#audit-outcome-levels" href="#audit-outcome-levels" id="toc-audit-outcome-levels">3. 审计结果水平差异</a>
<ul class="collapse">
<li><a class="nav-link" data-scroll-target="#三种定义与三种分母" href="#三种定义与三种分母" id="toc-三种定义与三种分母">3.1 三种定义与三种分母</a></li>
<li><a class="nav-link" data-scroll-target="#共同样本下的嵌套比较" href="#共同样本下的嵌套比较" id="toc-共同样本下的嵌套比较">3.2 共同样本下的嵌套比较</a></li>
</ul></li>
<li><a class="nav-link" data-scroll-target="#识别检验换入和换出四大后是否改善" href="#识别检验换入和换出四大后是否改善" id="toc-识别检验换入和换出四大后是否改善">4. 换所及PSM-DID：同一客户的变化</a>
<ul class="collapse">
<li><a class="nav-link" data-scroll-target="#三口径换入与换出" href="#三口径换入与换出" id="toc-三口径换入与换出">4.1 三口径换入与换出</a></li>
<li><a class="nav-link" data-scroll-target="#九项基线匹配did及支持诊断" href="#九项基线匹配did及支持诊断" id="toc-九项基线匹配did及支持诊断">4.2 九项基线匹配DID及支持诊断</a></li>
<li><a class="nav-link" data-scroll-target="#动态路径与修正的sa" href="#动态路径与修正的sa" id="toc-动态路径与修正的sa">4.3 动态路径与修正的SA</a></li>
</ul></li>
<li><a class="nav-link" data-scroll-target="#市场是否区别对待财报信息" href="#市场是否区别对待财报信息" id="toc-市场是否区别对待财报信息">5. 市场消息反应：门槛、斜率与固定水平差</a>
<ul class="collapse">
<li><a class="nav-link" data-scroll-target="#连续消息的正式检验" href="#连续消息的正式检验" id="toc-连续消息的正式检验">5.1 连续消息的正式检验</a></li>
<li><a class="nav-link" data-scroll-target="#门槛模型与消息可比性" href="#门槛模型与消息可比性" id="toc-门槛模型与消息可比性">5.2 门槛模型与消息可比性</a></li>
<li><a class="nav-link" data-scroll-target="#年度car曲线的展示对象" href="#年度car曲线的展示对象" id="toc-年度car曲线的展示对象">5.3 年度CAR曲线的展示对象</a></li>
</ul></li>
<li><a class="nav-link" data-scroll-target="#当前解释与待完成" href="#当前解释与待完成" id="toc-当前解释与待完成">6. 当前解释与待完成</a></li>
</ul>
</nav>
</div>
<!-- main -->
<main class="content" id="quarto-document-content">
<header class="quarto-title-block default" id="title-block-header">
<div class="quarto-title">
<h1 class="title">四大事务所效应</h1>
</div>
<div class="quarto-title-meta">
</div>
</header>
<section class="level2" id="概述">
<h2 class="anchored" data-anchor-id="概述">概述</h2>
<p>本章围绕一个问题组织两套结果：四大客户的审计失败更少，市场是否也对其盈利消息赋予更高权重？客户质量差异可以来自事前选择和审计服务；市场反应差异还可能来自盈利消息本身的经济内容。我们依次用可观察特征调整、年度客户匹配、换所与匹配 DID，以及门槛和连续盈余消息模型检验这些关系。</p>
</section>
<section class="level2" id="核心结果">
<h2 class="anchored" data-anchor-id="核心结果">核心结果</h2>
<p><strong>审计结果的优势在客户层面较明确，换所改善取决于失败定义和比较设计；市场反应在部分正式规格中为正，但其持续时间、大小和精度随估计对象变化。</strong> 因此，本章保留审计服务作用与客户选择两种解释，不把控制后剩余差异直接称为不可观察选择或私人信息认证。</p>
<ul>
<li><strong>可观察选择：</strong> 进入四大前三年，未来四大客户已有较大规模、较低亏损和违规发生率；临近进入时，重述没有同步改善。年度 PSM 的五项及九项选择模型均得到较低的三项未预警失败，但仍有尾部不平衡。</li>
<li><strong>换所结果：</strong> 九项匹配 DID 的中间口径综合失败和重述分别下降 11.85 和 9.11 个百分点，在逐批次剔除中方向及95%区间稳定。严格综合失败下降5.28个百分点，但对2017批次较敏感；严格重述、违规和宽口径结果保留非显著区间。</li>
<li><strong>市场消息：</strong> 连续线性 CAR 模型中，surprise 每增加10个百分点，四大相对 Other 的公告日额外反应为0.0084个百分点；固定 surprise=0.10 时的组间水平差为0.1868个百分点。两者均有正式检验，但不是同一估计量。门槛、共同支持筛选和非线性水平差分别报告。</li>
</ul>
</section>
<section class="level2" id="literature-feasible-baseline">
<h2 class="anchored" data-anchor-id="literature-feasible-baseline">1. 文献中现有数据可行的基础做法</h2>
<p>本章用两套结果回答同一个问题：<strong>四大身份是否对应更可靠的财务报告，以及市场是否对其盈利消息赋予更高权重？</strong> 失败率衡量事后结果，ERC 衡量价格对消息的敏感度，两者并非必须同时显著才能构成有意义的证据；但任一结果也不能独自分开审计服务、客户选择与消息经济内容。特别是“调整后仍有差异”不等于已经识别不可观察选择，更不等于市场获得了审计师的私人筛选信息。</p>
<p>文献中的基础路线是：先明确客户总体、结果变量与时点，比较客户特征和结果；再用控制或匹配调整可观察差异；随后以同一客户的变化及可解释的组织事件考察处理作用。市场部分直接估计连续盈利消息与审计师身份的交互，并区分消息斜率与固定消息下的水平差。分析师预测的准确度、分歧及信息更新是另外一类结果，不与公告 CAR 混用。</p>
<p>下面每组中文表分别列出 <strong>A：文献的数据与具体方法；B：我们已经实施的对应比较、定义差别及尚未完成的部分</strong>，使用相同论文编号和顺序。中文逐篇说明就在本节展开，包含完整作者、发表/工作稿版本、原文页码、正式来源及可复制检索词。文献并不提供一套可直接套用的“解决 selection”程序：匹配依赖共同支持与条件可交换性，DID 依赖适当趋势，IMR/IV 还需要额外的结构及排除限制。</p>
<section class="level3" id="客户特征匹配与失败指标">
<h3 class="anchored" data-anchor-id="客户特征匹配与失败指标">1.1 客户特征、匹配与失败指标</h3>
<p><strong>A．文献的数据与方法</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>国家、资料与样本</th>
<th>结果及测量时点</th>
<th>选择处理、模型与推断</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R04：Lawrence、Minutti-Meza、Zhang (2011)</td>
<td>美国上市公司，1988—2006；Compustat、CRSP、I/B/E/S。异常应计分析：匹配前72,600公司年度，匹配后21,130条（10,565对）；其他结果各用自己的样本。</td>
<td>业绩调整后的 modified Jones 异常应计绝对值、隐含权益资本成本、分析师预测准确度。应计调整减去同业同年中 ROA 最近客户的残差。</td>
<td>四大选择 Logit：资产、周转率、流动性、杠杆、ROA、结果特定控制、行业/年份。非四大向四大1:1匹配，无放回，原始得分卡尺0.03。应计结果使用行业/年份固定效应，公司聚类。</td>
</tr>
<tr class="even">
<td>R05：DeFond、Erkens、Zhang (2017)</td>
<td>美国上市公司；复制1988—2006，并扩展2004—2013；Compustat、Audit Analytics。样本量随结果和设计变化，无统一N。</td>
<td>绝对/正向异常应计、重大向下重述、困境客户的持续经营意见；同时比较平衡、保留样本与统计功效。</td>
<td>比较1:1、1:2、1:3、有/无放回、非线性选择模型及0—30%得分标准差卡尺；各放回条件形成1,500个平衡设计。结果特定控制，公司聚类。原始距离0.03不同于0.2倍标准差。</td>
</tr>
<tr class="odd">
<td>R06：Eshleman、Guo (2014)</td>
<td>美国公众公司，2000—2009；Compustat、Audit Analytics。主保留样本37,488，匹配5,950；四大与 BDO/Grant Thornton 比较31,346，匹配3,248。</td>
<td>审计财年后来重述、向下重述和 SEC 会计执法公告（AAER）；与异常应计代理不同。</td>
<td>逐年审计师选择 Logit；非四大向四大在同年、两位 SIC 内有放回匹配，卡尺0.01。结果 Probit 加融资、治理、费用等控制及行业/年份固定效应；公司/年份双向聚类。</td>
</tr>
</tbody>
</table>
<p><strong>B．项目对应与差别</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>我们已实施的比较</th>
<th>定义与设计差别</th>
<th>当前状态及识别缺口</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R04：Lawrence、Minutti-Meza、Zhang (2011)</td>
<td>已估计五项/九项年度 PSM 及共同样本结果回归，比较当年四大与匹配非四大客户。</td>
<td>本项目估计四大 ATET，有放回、无卡尺；行业/年份进入得分模型而非精确匹配。失败指标不同于原文三类代理。</td>
<td>完成的是相关比较，未完全复现。匹配改变共同支持和比较总体；剩余差异不能量化不可观察选择。</td>
</tr>
<tr class="even">
<td>R05：DeFond、Erkens、Zhang (2017)</td>
<td>已估计获授权的五项/九项年度选择模型，记录平衡、对照复用和有效样本量。</td>
<td>未搜索1,500种设计，也不按结果符号选规格。九项进入事件匹配是独立基线，不能用年度 PSM 替代。</td>
<td>仅完成明确列出的设计比较。尾部不平衡和对照权重集中仍需解释；匹配成功不证明条件可交换性。</td>
</tr>
<tr class="odd">
<td>R06：Eshleman、Guo (2014)</td>
<td>已构造重述/违规结果并估计年度四大 PSM；三种重述定义与未预警联合事件分别报告。</td>
<td>目前无精确同年同业限制或卡尺；AI 稳健标准误并非公司/年份聚类。违规不等于 SEC AAER，严格重述也更窄。</td>
<td>有对应的失败结果证据；未完全复制原文样本、控制、事件定义和推断。</td>
</tr>
</tbody>
</table>
<details>
<summary>
R04：Lawrence, Minutti-Meza and Zhang (2011)｜中文逐篇说明、原文定位与检索词
</summary>
<p>Alastair Lawrence、Miguel Minutti-Meza、Ping Zhang，<em>Can Big 4 versus Non-Big 4 Differences in Audit-Quality Proxies Be Attributed to Client Characteristics?</em>，<strong>The Accounting Review 86(1):259–286</strong>，正式发表。<a href="https://doi.org/10.2308/accr.00000009">出版登记</a>。检索：<code>"Can Big 4 versus Non-Big 4 Differences" Lawrence Minutti-Meza Zhang</code>。</p>
<ul>
<li>国家、层级、数据；美国上市公司—年度，1988–2006；Compustat，收益与分析师相关Y另需CRSP/I/B/E/S。年度财务报表审计，不是事务所全客户总体</li>
<li>样本；DA分析全样本72,600公司年；主匹配21,130公司年＝10,565对。其他Y依赖各自数据，不能沿用这个N；其精确N本轮未逐表重核</li>
<li>Y与时点；绝对可操纵应计、隐含权益资本成本、分析师预测准确度。DA按报告年度；资本成本/预测Y不能统一称为财报年度内发生的审计失败</li>
<li>DA构造；行业—年modified Jones及Kothari式业绩调整：先估计应计残差，再减去行业—年内ROA最接近客户的残差；Y取绝对值。总应计和相应项按资产缩放，具体分母应按原式核对，不能替换为项目现有DA后称完全复刻</li>
<li>选择模型；Big4 logit：LOG_ASSETS、ATURN、CURR、LEV、ROA，加相应Y的控制、行业/年指示变量；重复控制在主设定处理，另有保留重复项/probit敏感性</li>
<li>匹配细节；主方法每个非四大找四大最近邻，1:1、无放回、原始倾向得分距离≤0.03。行业/年进入模型不等于精确同业同年匹配；另作精确匹配敏感性</li>
<li>结果模型；DA模型含Big4、log市场价值、滞后ROA/杠杆/流动比率、行业/年FE；公司聚类。其他Y模型控制不同，不应套用DA清单</li>
<li>额外尝试；RESET非线性项、单项客户特征匹配、核/加权、选择模型及bootstrap等。客户规模的作用是核心比较之一</li>
<li>原文定位；正式pp.262–265（附件PDF pp.4–7），§III、DA变量/回归式、匹配表及敏感性分析</li>
</ul>
<p>原文主要用于说明客户特征尤其规模能解释部分审计质量代理差异；不能把“匹配后不显著”直接解释为真实处理效应为零。匹配改变了支持区间与估计总体，且未观察选择仍在；当年X也可能受审计/披露影响。</p>
</details>
<details>
<summary>
R05：DeFond, Erkens and Zhang (2017)｜中文逐篇说明、原文定位与检索词
</summary>
<p>Mark DeFond、David H. Erkens、Jieying Zhang，<em>Do Client Characteristics Really Drive the Big N Audit Quality Effect? New Evidence from Propensity Score Matching</em>，<strong>Management Science 63(11):3628–3649</strong>。正式刊期2017，2016-09-07上线；出版商引用栏使用2016，本文按刊期2017登记，不把工作论文年份混入。<a href="https://pubsonline.informs.org/doi/10.1287/mnsc.2016.2528">出版商与版本日期</a>。检索：<code>"Do Client Characteristics Really Drive" DeFond Erkens Zhang</code>。</p>
<ul>
<li>样本/来源；美国上市公司—年度；复制1988–2006并扩展2004–2013，Compustat/Audit Analytics等。N随Y、匹配设计与放回规则变化，不能报告一个统一样本N</li>
<li>Y；绝对/正向异常应计、重大向下重述、财务困境客户的持续经营意见；后两者分别是后续发现的报告问题与年度审计意见，GC仅在困境子样本解释</li>
<li>初始选择变量；规模、ROA、杠杆、流动比率、资产周转率；初始复制1:1无放回、得分距离0.03</li>
<li>设计变动；1:1/1:2/1:3；卡尺0–30%倾向得分标准差；随机二次/三次/交互项；有/无放回。0.03原始距离与0.2倍SD是不同量纲</li>
<li>平衡和功效；各有/无放回条件下形成1,500个平衡迭代；变量均值t检验p&gt;0.10，并检查标准化偏差、L1、保留N和控制重复使用；另讨论中等效应的统计功效</li>
<li>结果模型；按匹配设计的概率权重估计，公司聚类；各Y回归控制见附录A/B。本轮未重新穷尽每个Y的全部控制名，不应从五项选择变量推定结果模型只有五项</li>
<li>数据处理；比较先对基础项目缩尾再构造比率与先构造比率再缩尾；讨论行业—年最小观测数、异常应计筛选及代理有效性。这些是复现差异，不是授权项目改口径</li>
<li>原文定位；正式pp.3631–3637，Table 2及设计敏感性表、附录A/B；附件PDF p.5对应p.3632</li>
</ul>
<p>多数合格设计仍支持Big N质量优势的关联。本文反驳的是“某一次PSM消除差异足以证明完全选择解释”，并未通过随机冲击消除未观察选择。不同合格设计结果都应呈现；不能挑出最显著设计作主结果。</p>
</details>
<details>
<summary>
R06：Eshleman and Guo (2014)｜中文逐篇说明、原文定位与检索词
</summary>
<p>John Daniel Eshleman、Peng Guo，<em>Do Big 4 Auditors Provide Higher Audit Quality after Controlling for the Endogenous Choice of Auditor?</em>，<strong>AUDITING: A Journal of Practice &amp; Theory 33(4):197–219</strong>，正式发表。<a href="https://doi.org/10.2308/ajpt-50792">出版登记</a>。检索：<code>"Do Big 4 Auditors Provide Higher Audit Quality" Eshleman Guo</code>。</p>
<ul>
<li>国家/数据/期间；美国上市公司—年度，2000–2009，Compustat Fundamentals＋Audit Analytics；财务报表重述关联到原报告年度</li>
<li>筛选/N；90,634起始；依次减14,832金融、1,599重大内控缺陷、6,395换所年度、30,320缺失＝37,488。匹配后5,950；Big4对BDO/Grant Thornton另为31,346全样本、3,248匹配样本</li>
<li>Y；RESTATE：某年度财务报表以后是否被重述；另检验向下重述和AAER。披露/查获年度不能替代原财报年度</li>
<li>选择；每年Big4 logit，LNASSETS、ATURN、ROA、LEV、CURR及结果控制；每个非Big4找Big4，同年同两位SIC，最近邻、有放回、得分卡尺0.01</li>
<li>结果模型；Probit；控制LNASSETS、ATURN、ROA、LEV、CURR、BM、FIN、EPSGROW、EP、FREEC、AGE、QUAL、INFLUENCE、LNFEE；行业/年FE，公司和年份双向聚类</li>
<li>敏感性；卡尺0.02/0.03/0.05/0.10/0.20/0.25，重复控制项、其他失败代理、Big4对第二梯队比较</li>
<li>分类；Andersen退出前属Big4/历史大所分类处理；不能直接按项目现行四大品牌定义代入历史样本</li>
<li>原文定位；正式pp.202–205（PDF pp.6–9），样本流程、Eq.(2)、主匹配表/表注</li>
</ul>
<p>这篇结果说明更严重失败代理和匹配设定会改变结论；“controlling endogenous choice”是其研究目标，不等于随机化。排除换所年意味着主要不是聘用四大前后的进入设计。</p>
</details>
</section>
<section class="level3" id="长期风险与事务所客户选择">
<h3 class="anchored" data-anchor-id="长期风险与事务所客户选择">1.2 长期风险与事务所客户选择</h3>
<p><strong>A．文献的数据与方法</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>国家、资料与样本</th>
<th>结果及测量时点</th>
<th>选择处理、模型与推断</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R11：Lennox、Pittman (2010)</td>
<td>美国上市公司，1981—2001；SEC AAER、LexisNexis，发现记录到2006年10月。508家舞弊公司、1,109个舞弊公司年度、162,804个非舞弊年度；各回归N不同。</td>
<td>舞弊归属于发生年，而非发现年；另比较长期任期与事务所更换。</td>
<td>舞弊 Probit，年份/公司效应，公司聚类。聘用 Big 5 的匹配与舞弊风险匹配不同；后者用最后一个非舞弊年度。卡尺/放回细节未核实。跨层换所仅46/11次。</td>
</tr>
<tr class="even">
<td>R10：Johnstone、Bedard (2004)</td>
<td>美国一家大型事务所的内部客户组合，含上市与私人客户，2000—2001；超过7,000家，精确总数保密。事务所终止43家、新接424家，排除375条缺失。</td>
<td>事务所主动终止与留任、新客户接受与留任、终止与新接客户之间的比较。</td>
<td>Logit 使用私有战略风险、财报风险、管理层诚信评分，以及公共财务、费用和行业变量。完整固定效应/标准误规则未核实，不能写成“没有”。</td>
</tr>
</tbody>
</table>
<p><strong>B．项目对应与差别</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>我们已实施的比较</th>
<th>定义与设计差别</th>
<th>当前状态及识别缺口</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R11：Lennox、Pittman (2010)</td>
<td>已有按涉及财年归属的失败、进入前轨迹、意见与客户流动证据。</td>
<td>重述/违规比 SEC 舞弊更宽；稳定合格进入不同于原文舞弊风险匹配或全部换所。</td>
<td>可对照事件时点与风险集；没有精确舞弊风险匹配或随机审计师分配。</td>
</tr>
<tr class="even">
<td>R10：Johnstone、Bedard (2004)</td>
<td>已有公共数据的相邻年度进入/退出、MAO/GC 回归及变更公告案例。</td>
<td>退出四大不能辨明谁发起更换；公开公告不能恢复内部评分及完整接受/终止风险集。</td>
<td>已估计选择相关关联；当前退出指标尚未识别事务所主动拒收或终止。</td>
</tr>
</tbody>
</table>
<details>
<summary>
R11：Lennox and Pittman (2010)｜中文逐篇说明、原文定位与检索词
</summary>
<p>Clive Lennox、Jeffrey A. Pittman，<em>Big Five Audits and Accounting Fraud</em>，<strong>Contemporary Accounting Research 27(1):209–247</strong>，使用正式版。<a href="https://doi.org/10.1111/j.1911-3846.2010.01007.x">出版登记</a>。检索：<code>"Big Five Audits and Accounting Fraud" Lennox Pittman</code>。</p>
<ul>
<li>数据/期间；美国上市公司年报，1981–2001；SEC AAER、LexisNexis追查至2006-10-31，识别舞弊实际发生年，Compustat客户特征</li>
<li>样本；508舞弊公司、1,109舞弊公司年、162,804无舞弊公司年；加控制后的回归N可能更少，不将这些数直接等同每一列e(sample)</li>
<li>Y；Fraud：报告年度是否涉及会计舞弊；不是查获年度、审计意见，也不是普通盈余预测误差</li>
<li>基础模型；Fraud probit，Big5及年/公司效应、客户控制；标准误公司聚类。控制涉及log资产、log公司年龄、审计任期、负权益、收购、重大债/股融资、亏损等；完整逐列清单本轮未穷尽</li>
<li>匹配A；估计聘用Big5倾向，对非Big5客户匹配Big5客户；完整第一阶段结果未表列。卡尺/是否放回本轮未确认，不沿用其他论文设定</li>
<li>匹配B；按最后一个无舞弊年度特征估计舞弊倾向，匹配舞弊与非舞弊公司后重新检验Big5；这不是再次匹配Big5选择</li>
<li>时序/更换检验；区分长短聘任（中位任期5年）；查看舞弊年及此前3年更换方向、辞任/解聘。46次更换中11次非同梯队更换，需注意检验功效</li>
<li>原文定位；正式版数据/研究设计、Table 3匹配、Table 7任期与Table 8更换；不沿用早期稿表号</li>
</ul>
<p>长任期与舞弊前的更换分析削弱某些反向因果故事，但不能排除持续的客户质量差异和审计师长期筛选。原文较强因果表述与本报告识别评价应分开。</p>
</details>
<details>
<summary>
R10：Johnstone and Bedard (2004)｜中文逐篇说明、原文定位与检索词
</summary>
<p>Karla M. Johnstone、Jean C. Bedard，<em>Audit Firm Portfolio Management Decisions</em>，<strong>Journal of Accounting Research 42(4):659–690</strong>，正式版。<a href="https://onlinelibrary.wiley.com/doi/10.1111/j.1475-679X.2004.00153.x">出版商</a>。检索：<code>"Audit Firm Portfolio Management Decisions" Johnstone Bedard</code>。</p>
<ul>
<li>国家/总体；美国一家大型审计所内部客户总体，含上市及私人客户；2000–2001客户接纳/续约期间，不是只含上市年报的公开数据库</li>
<li>N/筛选；缺失资料剔除375；保留超过7,000客户，精确总N因保密未披露；43个所方终止、424新客户、其余继续，不根据模糊总量反推确数</li>
<li>Y；终止对继续、终止对新接纳、新接纳对继续的二元选择；不是审计后DA、舞弊或四大采用</li>
<li>私有风险指标；STRATEGICPOSITION为14项1–5风险响应均值；CONTROLS为内部控制有效性1–5评分；FINRPTNG为19项财报风险是/否求和；MGTINTEG为9项管理层诚信风险求和</li>
<li>其他X；上市客户财务杠杆/ROA，PUBLIC、计划费用/小时BILLRATE、资产及零售/金融/制造/高科技/其他行业；财务指标±3SD处理，不是1/99缩尾</li>
<li>模型/FE-SE；二元logit；本轮未确认FE/聚类完整细节，不能写作“公司聚类”或“无FE”</li>
<li>原文定位；客户分类、内部风险量表、研究设计与接纳/继续/终止结果表；细分私有量表不能用公开ROA替代并称同一指标</li>
</ul>
<p>所方主动终止高风险客户说明供给端筛选真实存在。它不证明所有四大质量差异都由筛选引起，也没有估计接受四大的平均处理效应。</p>
</details>
</section>
<section class="level3" id="中国审计前质量审计调整与制度环境">
<h3 class="anchored" data-anchor-id="中国审计前质量审计调整与制度环境">1.3 中国：审计前质量、审计调整与制度环境</h3>
<p><strong>A．文献的数据与方法</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>国家、资料与样本</th>
<th>结果及测量时点</th>
<th>选择处理、模型与推断</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R09：Chen、Krishnan、Li、Zhang (2022)</td>
<td>中国上市公司，2006—2011；CICPA 私有审计前后报表、CSMAR/Wind、审计师资料。初始10,466公司年度，保留6,323。</td>
<td>审计前异常应计/ROE、审后有符号异常应计、后续财年重述、MAO、向下利润调整；调整额按 CFO/审前资产缩放。</td>
<td>选择 Logit 加审前质量、财务、所有权、制度变量；结果模型加审前质量。熵平衡选择协变量均值；行业/年份固定效应、公司聚类、1%/99%缩尾。不是 PSM/IV。</td>
</tr>
<tr class="even">
<td>C16：Lennox、Wu、Zhang (2016)</td>
<td>中国上市公司，2006—2012；财政部私有审计前后利润/资产及 CSMAR CFO。主样本11,486，含205个金融公司年度；持续性样本8,569。</td>
<td>配对审前/审后 ROA、平滑、持续性、应计质量；同一审后 CFO 分子分别按审前/审后资产缩放。</td>
<td>在同一套报表内比较审前后性质；平滑要求至少四个连续年份。持续性斜率按公司聚类，非本项目九项控制的固定效应 DID。处理对象是审计调整，而非四大聘用。</td>
</tr>
<tr class="odd">
<td>R12：Ke、Lennox、Xin (2015)</td>
<td>中国四大上市客户，1995—2012；A/B/H 报告、CSMAR、CICPA。1,280公司年度：较弱环境910，独立 H 股审计师的 AH 较强环境370；各结果N不同。</td>
<td>相对审计师经验、意见、对数费用、有符号异常营运资本/Jones 应计；在四大内部比较制度环境。</td>
<td>AH 选择 Probit 含18项财务、所有权、复杂度协变量；最近得分距离小于0.01，331对，排除39个处理观测。公司聚类、1%/99%缩尾。工作稿的放回/精确匹配及全部结果固定效应未核实。</td>
</tr>
</tbody>
</table>
<p><strong>B．项目对应与差别</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>我们已实施的比较</th>
<th>定义与设计差别</th>
<th>当前状态及识别缺口</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R09：Chen、Krishnan、Li、Zhang (2022)</td>
<td>已有审后应计、意见、三种重述及共同样本嵌套回归。</td>
<td>项目没有原文私有审前报表/调整；公共协变量不直接测量审前盈余质量。有符号应计也不同于绝对值。</td>
<td>未声称完成私有审前后复现或熵平衡估计；剩余结果差异不证明没有不可观察选择。</td>
</tr>
<tr class="even">
<td>C16：Lennox、Wu、Zhang (2016)</td>
<td>已有审后 DA/CFO 及多种盈余质量指标，普通和匹配换所比较已经估计。</td>
<td>缺少私有审前报表配对；更换事务所不同于测量本次审计已入账的调整。</td>
<td>公共数据不能恢复这项直接审计前后比较；原文是测量参照，不是已完成的四大因果复现。</td>
</tr>
<tr class="odd">
<td>R12：Ke、Lennox、Xin (2015)</td>
<td>已有事务所类别、费用、意见、DA；官方审计师 ID 支持覆盖诊断。</td>
<td>四大/非四大不同于四大内部 AH 与纯A/AB比较；独立 H 股审计师分类及相对经验排名未复现。</td>
<td>没有精确制度环境匹配样本；正式2015书目已核实，方法细节按已指明工作稿登记。</td>
</tr>
</tbody>
</table>
<details>
<summary>
R09：Chen, Krishnan, Li and Zhang (2022)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>Songsheng Chen, Gopal V. Krishnan, Wenying Li, Yinqi Zhang.</strong> <em>Do Big 4 Auditors Enhance Audit Quality in China? A “Behind the Scenes Look”</em>. Journal of International Accounting Research 21(2), 31–56，正式发表2022；本地附件为正式排版。在线核验：<a href="https://doi.org/10.2308/JIAR-2020-056">DOI/出版商入口</a>、<a href="https://www.american.edu/uploads/resume/cv_yinqizhang_dec24.pdf">作者机构CV</a>。本轮出版商/完整CV访问有限，但实时搜索可检索作者CV记录；正式全文首页提供作者、年份、卷期页码。SSRN 3577732的旧工作论文题目不同，不能混同其结论与正式版。复制搜索词：<code>"Do Big 4 Auditors Enhance Audit Quality in China" "Songsheng Chen"</code>。</p>
<p>全文依据：本地原文核对件；PDF6—8（刊页36—38）样本及模型，PDF12/表3—4结果，PDF21—22/表7审前后质量，PDF26—27变量附录。</p>
<p><strong>数据与样本。</strong> CICPA私有数据记录审计前后资产、权益、税前利润、应付税款及签字人属性；CSMAR用于财务与审计所信息，重述亦用Wind，事务所合并手工查CSRC/CICPA。2006—2011初始10,466公司年，删H股371、金融197、审计师属性缺失1,145、其他变量缺失2,430，留下6,323。作者没有提供可由本文逐行恢复的完整公司名单；不能将其视为CSMAR全客户宇宙。</p>
<p><strong>Y构造。</strong> 审前NI=审前税前利润×(1−法定税率)。审前总应计用审前NI−CFO，并以审前资产标准化，通过modified Jones得到PREDAC；其分母与本项目上一年资产不同，完整第一阶段分组和实现细节未充分披露。PREROE=1表示审前NI/审前权益在[0,.02]或[.06,.08]。POSTDAC为审后有符号DA，不能直接以绝对DA替代。RESTA=当前财年的报表随后被重述，不要求本项目严格口径中的“盈余调整方向明确非零”。MAO包含带解释段的无保留、保留、无法表示、否定意见。</p>
<p>直接调整Y为DWNAJ_DUM、DWNAJ_CF、DWNAJ_TA：是否向下调整NI、(审前NI−审后NI)/|CFO|、(审前NI−审后NI)/审前资产。直接调整与事后重述含义不同：前者是在本次审计中发现并入账，后者是后续披露的报表问题。</p>
<p><strong>选择模型（原文式1）。</strong> Logit的因变量BIG4，独立变量为PREDAC、PREROE、SIZE、LEVERAGE、ROA、ATURN、LLOSS、LMAO、CURR、GROWTH、ISSUE、SOE、FOREIGN、CONTROL、GEO，另加年和行业。SIZE为log当年资产；ROA/ATURN分别以当年资产标准化；LLOSS/LMAO是上一年；CURR为流动资产/流动负债；ISSUE为当年发行；FOREIGN为B/H股；CONTROL为主导股东份额；GEO为省级市场发展指数的log。负PREDAC或PREROE系数指向较高审前质量客户与Big4匹配，不区分供需两侧筛选。</p>
<p><strong>结果模型（式2—3）。</strong> POSTDAC/RESTA先用BIG4与财务控制，再加入PREDAC/PREROE；MAO/调整模型直接控制审前质量。控制包括SIZE、LNAGE、LEVERAGE、ROA、LOSS、ATURN、ISSUE、SUBSID、SOE、FOREIGN、CONTROL、GEO、TENURE、AUDITMA、MROTFIRST、MROTFINAL、SPECIALIST、INFLUENCE；重述模型加LRESTA，意见模型加LMAO。年与行业FE、公司聚类；连续变量1%/99%缩尾。SUBSID为log(1+子公司数)，TENURE为所任期log；SPECIALIST考虑任一签字人在行业内按客户资产的份额领先，INFLUENCE指客户为任一签字人的最大收费客户。不能把签字人专长误当审计所专长。</p>
<p><strong>熵平衡（PDF8）。</strong> 平衡式1全部独立变量的均值，估计式2—3，并比较全样本和四大/本土Top4组成的Top8样本。原文并未在此说明高阶矩平衡，不能自行补成方差、偏度约束；这也不是PSM、Heckman或IV。处理前质量测量有噪声，且年度审计之前四大可能已参与中期工作；“审前”并非必然完全未经当期审计影响。</p>
<p><strong>document与边界。</strong> 在主要全样本及Top8比较中，加审前质量后，Big4与较低POSTDAC的关系消失，较低RESTA关系保留；四大向下调整更少。PDF8脚注11说明，与非Top4本土所比较时，控制PREDAC后POSTDAC关系仍可保留，不能声称所有对照选择下均消失。表7又比较审前后持续性、应计质量。结果说明衡量不同Y会得到不同判断，不能选其中一个Y写成普遍因果效果，也不能用“加入审前质量后仍显著”排除所有反向因果。</p>
</details>
<details>
<summary>
C16：Lennox, Wu and Zhang (2016)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>Clive Lennox, Xi Wu, Tianyu Zhang.</strong> <em>The effect of audit adjustments on earnings quality: Evidence from China</em>. Journal of Accounting and Economics 61(2–3), 545–562；2015-08-28 online，正式2016-04-01。<a href="https://researchportal.bath.ac.uk/en/publications/the-effect-of-audit-adjustments-on-earnings-quality-evidence-from/">机构正式记录</a>。本地为2015 online-first排版，下面用PDF页码，不强行映射正式刊页。搜索词：<code>"The effect of audit adjustments on earnings quality" "Lennox" "Wu" "Zhang"</code>。</p>
<p>本地原文核对件；PDF5—6样本与报表核对，PDF9—11/表3—5平滑、持续性、应计质量，PDF17讨论。</p>
<p><strong>数据与样本。</strong> MOF私有审前/审后税前利润与资产，2006—2012；2012另有负债和权益调整；CSMAR提供CFO。CSMAR13,231、MOF12,495公司年，交集12,258；审后利润在两库不一致超过约±5%者772条被排除，最终11,486，含205金融公司年。另做±1%核对敏感性；人工核查发现部分母公司/合并范围混淆等。年度Big10按上市客户资产排名，不是固定Big4，也不是项目本土八大。</p>
<p><strong>指标与方程。</strong> PRE_ROA=审前税前利润/审前当年资产；POST_ROA同理用审后资产。两个CFO指标使用同一审后CSMAR现金流分子，但分别除以审前/后资产；须保留这一假设，不能说观察到了审前CFO。</p>
<ol type="1">
<li>平滑：比较|ΔPRE_ROA|与|ΔPOST_ROA|，再各除以|ΔPRE_CFO|/|ΔPOST_CFO|。需要相邻两年；公司层面的SD(ΔROA)及SD(ΔROA)/SD(ΔCFO)至少四个连续年份。与项目四年水平NI/CFO标准差比率并非同一Y，也不能直接以“平滑越高质量越差”解释本文。</li>
<li>持续性：PRE_ROA[t+1]=a0+a1PRE_ROA[t]+e；POST_ROA[t+1]=b0+b1POST_ROA[t]+e，检验a1=b1。表4是简单持续性方程，没有把项目九项控制、公司FE加到原文模型中。8,569公司年，总样本审前斜率0.333、审后0.413，差异检验p&lt;.001；标准误公司聚类。</li>
<li>应计质量：PRE_ACCRUALS=a0+a1PRE_CFO[t−1]+a2PRE_CFO[t]+a3PRE_CFO[t+1]+u_PRE；POST同式。比较残差绝对值和波动；分母分别为对应审前/后资产，使用的是文中定义的总应计，不自动等于CSMAR WCA-DD模型。具体全部分组细节若未在当前核对页明确，不补写。</li>
<li>另比较有符号及绝对应计和零盈余分布。审计调整对signed与absolute accruals的影响不同，使用|DA|可能漏掉方向变化。</li>
</ol>
<p>表3变化指标标准误公司聚类；公司标准差比较为公司层面。其他检验的SE不应一概套同一说明。该文没有用PSM或IV工具化Big4分配；没有证据时不补写输入缩尾规则。</p>
<p><strong>识别与项目对应。</strong> 配对消除了把不同公司基准混为调整的问题，直接观察已入账调整，但没有随机分配客户到Big4。项目只能计算审后持续性/平滑等可比描述，无法实施原文私有审前后配对。与陈文相同，私有数据只解释识别边界，不列为当前必须补购的公共变量。</p>
</details>
<details>
<summary>
R12：Ke, Lennox and Xin (2015)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>Bin Ke, Clive S. Lennox, Qingquan Xin.</strong> <em>The Effect of China’s Weak Institutional Environment on the Quality of Big 4 Audits</em>. The Accounting Review 90(4), 1591–1619；2014 online、正式2015。<a href="https://researchportal.bath.ac.uk/en/publications/the-effect-of-chinas-weak-institutional-environment-on-the-qualit/">机构正式记录</a>。<strong>本地51页附件为SSRN工作论文2510211</strong>，不能把下面实现细节都声称已在最终版核对。搜索词：<code>"The Effect of China's Weak Institutional Environment on the Quality of Big 4 Audits" "Bin Ke"</code>；SSRN：<code>2510211</code>。</p>
<p>本地原文核对件；PDF19—23原始模型/样本，PDF29—30式7匹配，PDF39—42变量/样本表，PDF49—51表8匹配；印刷页码通常比PDF小2。</p>
<p><strong>数据、报告与筛选。</strong> 中国上市公司Big4年度A股审计，1995—2012；CSMAR、年报及A/B/H报表、CICPA个人资料。1,414删金融125、新加坡7、香港非四大2，剩1,280。弱环境910=纯A553+AB331+没有独立H审计的AH26；强环境370为有独立H审计的AH。经验Y可用1,185；意见1,280；费817（2001前未披露166、未披露23、A/H/B费未单列274）；应计1,214。不是每个回归N均为1,280，更不是全部审计客户。</p>
<p><strong>Y构造。</strong> EXPERIENCE为两名签字人相对经验均值；经验按签过至少一个上市审计的年份积累，在所×年内排名，REL_YEARS=100−(rank−1)/(Njt−1)×100。OPINION为非干净意见；费用取log；AWCA及DA_Jones为有符号应计。正文Jones与附录modified Jones表述并不提供可逐行复算的完整第一阶段，不能编写其AWCA/DA精确公式。</p>
<p><strong>匹配模型与操作（式7/表8）。</strong> 表8明确probit，AH为1；变量SIZE、LEV、ROE、LOSS、MB、SALESGROWTH、SOE、CAPE、LSHARE、NSUB、FOROPS、log segments、CURRENT、ARINV、RETURN、CASH、VOL、PC。CAPE=资本支出/资产，LSHARE最大股东份额；PC为董事长或CEO当前/曾经的政府或军队任职。VOL是市场模型残差方差，不应换成标准差；NSUB为子公司数平方根，不是log。找到每个AH观测的最近概率，绝对差严格&lt;0.01，删39对，留下331强+331弱。原文未明确有放回与否、额外年/行业精确匹配，不能自行补写。平衡表报告均值/中位数差异检验，不是本项目SMD≤10%的硬门槛。</p>
<p><strong>结果回归。</strong> 匹配后仍估计意见、经验、费用、应计模型，各Y控制集合不同；包含SIZE、LEV、ROE/LOSS、SOE及视模型而定的CURRENT、ARINV、RETURN、CASH、VOL、CFO、MB、NSUB、FOROPS、segments、DOUBLE等，不能把18项AH模型变量机械当成所有结果方程控制。公司聚类；连续变量1%/99%缩尾；年/行业处理应依各表，未逐表确认的规格不统一宣称。SHORT按上市/交叉上市初期分组的检验也不是外生随机处理。</p>
<p><strong>识别与项目对应。</strong> 已有签字人、费、意见、signed DA并不表示已有本文相对经验、AWCA和DOUBLE。还须核验A/B/H和独立H报告、两地办公室、境外上市日期、segments、政治关联。当前29是四大/非四大选择Logit，34是换入四大DID；都不是本文AH/制度环境匹配。本文PSM不能排除未观察跨境融资需求与治理质量的选择。</p>
</details>
</section>
<section class="level3" id="中国竞争所有权与监管背景">
<h3 class="anchored" data-anchor-id="中国竞争所有权与监管背景">1.4 中国：竞争、所有权与监管背景</h3>
<p><strong>A．文献的数据与方法</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>国家、资料与样本</th>
<th>结果及测量时点</th>
<th>选择处理、模型与推断</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R19：Xin、Liu、Tang (2023)</td>
<td>中国四大与本土 Big 6 上市客户，2003—2019；CSMAR/Wind/CICPA、手工费用。16,261公司年度、2,886公司；重述排除2019，N=14,401。</td>
<td>境内审计费对数、客户 Z-score、后续重述、绝对业绩调整异常应计。竞争使用各事务所平均份额差，而非集团总份额。</td>
<td>行业/年份/省份固定效应，公司聚类。本土 Big 6 合并 DID：前后各三年、排除事件年，N=8,970。仅t+1的合并 IV 用于费用/Z-score的竞争及四大交互，不是质量 IV。</td>
</tr>
<tr class="even">
<td>R13：Wang、Wong、Xia (2008)</td>
<td>中国纯A股，1993—2003；年报、证券报、CSMAR、手工所有权及 NERI 2000制度基准。5,759公司年度。</td>
<td>选择“小型本地事务所”：按当年客户资产不在前十，且与客户同省；比较中央/地方国企及制度。</td>
<td>Logit 含所有权/制度交互、财务、发行变量及行业/年份指示。主规格报告 Newey–West 一阶滞后；稳健性含年份聚类/Fama–MacBeth。转所表标准误尚未完整核实。</td>
</tr>
<tr class="odd">
<td>R18：Lisic、Silveri、Song、Wang (2015)</td>
<td>中国非金融上市公司，1999—2005；CSMAR监管舞弊、财务、审计资料。方法核读2013年10月工作稿，正式版逐表N未完整核验。</td>
<td>按发生年归属的舞弊、严重性、收入舞弊；事务所按年度资产排名前十，并非四大或 Local 8。</td>
<td>监管处罚背景下的舞弊模型，以及审计师选择/IMR扩展。完整第一阶段、各列固定效应/标准误和最终版本对应未核实，保留空缺。</td>
</tr>
</tbody>
</table>
<p><strong>B．项目对应与差别</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>我们已实施的比较</th>
<th>定义与设计差别</th>
<th>当前状态及识别缺口</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R19：Xin、Liu、Tang (2023)</td>
<td>已有费用、Z-score、DA、重述，以及普通四大换所和盈余质量比较。</td>
<td>Local 8 不等于原文随时间变化的本土 Big 6；尚未实施省级竞争构造、合并设计或竞争 IV。</td>
<td>原文识别的竞争处理不同。第一阶段F较强不验证排除限制，不能推为可用的四大聘用 IV。</td>
</tr>
<tr class="even">
<td>R13：Wang、Wong、Xia (2008)</td>
<td>已有较宽事务所类别、所有权字段；年度选择模型使用已授权财务控制。</td>
<td>Other 不等于小型本地事务所，二元 SOE 不等于中央/地方所有权；需独立构造历史排名、省份和制度。</td>
<td>提供审计师选择背景，不是四大处理结果；未复制精确历史选择模型。</td>
</tr>
<tr class="odd">
<td>R18：Lisic、Silveri、Song、Wang (2015)</td>
<td>已有发生年违规、严重/未预警失败代理及事务所组比较。</td>
<td>事件标记和固定类别不同于原文舞弊分类及逐年前十；尚未实施 IMR。</td>
<td>作为中国监管背景；工作稿不改称正式表证据，也不提供外生审计师选择工具。</td>
</tr>
</tbody>
</table>
<details>
<summary>
R19：Xin, Liu and Tang (2023)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>Qingquan Xin, Yu Liu, Yiheng Tang.</strong> <em>China’s audit market competition and the competitive strategies of the international Big 4 audit firms</em>. China Journal of Accounting Studies 11(3), 574–601；2023-08-01 online，正式2023。<a href="https://www.tandfonline.com/toc/rcja20/11/3">出版商卷期目录</a>、<a href="https://www.tandfonline.com/doi/pdf/10.1080/21697213.2023.2239675">正式PDF入口</a>。本轮PDF直接打开403，实时出版商检索条目及本地正式PDF核对元数据；不是凭摘要重构方法。搜索词：<code>"China’s audit market competition" "Qingquan Xin" "Yu Liu" "Yiheng Tang"</code>。</p>
<p>本地原文核对件；PDF9—11样本/竞争/控制，PDF18刊页590表6 DID/IV，PDF19—21其他分析，PDF29变量附录。</p>
<p><strong>样本与来源。</strong> 2003—2019，Big4与本土Big6上市客户；CSMAR财务/审计，缺失费从年报/聘任公告补，Wind治理，CICPA年度排名识别本土Big6。剔金融、ST、缺失，16,261公司年、2,886家公司；原文没有初始N及逐步删除N。后续重述回归删2019，N=14,401；不能将1,860条差额全部归因某一步而猜补流程。</p>
<p><strong>Y与竞争。</strong> Fee=log年度境内费；ZScore=1.2(流动资产−流动负债)/A+1.4留存收益/A+3.3EBIT/A+.6市值/负债+.999收入/A。RESTA为本年度随后重述。绝对DA用Kothari2005 modified Jones，但ROA回归控制还是performance matching及第一阶段阈值顺序未充分披露，不能把当前CSMAR Jones当成原文同一指标。Comp_af/ta为前一年省级四大和本土Big6<strong>平均事务所份额差绝对值的负值</strong>（分别收费/客户资产）；不是两组总份额简单相减。竞争越接近为0越强。</p>
<p><strong>控制与规格。</strong> Switch、意见及部分复杂度变量用于费模型，质量模型的控制集合不同；附录包括第二签字人行业/省份收费专长、Lnsub、上市Age、Dual、SOE、SIZE、LEV、ROI、LOSS、Cata、Quick、长期债、INV、intang、growth、省GDP、市场化。年/行业/省份FE，公司聚类，连续变量1%/99%缩尾。没有公司FE的省级竞争回归不能写成项目公司FE规格。</p>
<p><strong>DID（表6）。</strong> 本土Big6首次合并、省内Big4与Big6差异反应；pre=t−3、t−2、t−1，post=t+1、t+2、t+3，删t=0。窗口要求限制样本期2006—2016，8,970公司年；多次合并仅以首次定Post。Fee的Big4×Post=−.097（t=−2.64），ZScore为−.547（t=−2.76）。控制同表，年/行业/省份FE，公司聚类。原表星号与正文显著性概述可能不同，采用表内数值，不自行推精确p值。未提供现代分期DID的动态lead/lag联合检验，因此不能描述成已检验充分的平行趋势。</p>
<p><strong>IV（表6）。</strong> Merger在省内合并后第一年t+1为1，否则0；用Merger及Merger×Big4对应竞争及其Big4交互，第二阶段仍解释Fee/ZScore。表中Cragg–Donald F为22.974、22.862；交互系数分别−7.139（t=−2.30）、−6.433（t=−2.06）。F说明相关性检验结果，不能证明排除限制。作者理由是本土Big6合并由本土所决定、不直接改变Big4行为；这是一项需要辩护的假设。合并可能直接改变审计资源、客户流动、收费或能力，所以不能不加论证把它移作客户Big4选择的IV。</p>
<p>进一步新客户子样本和change-on-change检查客户风险/收费变化，仍不等于随机客户筛选；2007前后异质性也不自动构成外生Big4处理。</p>
</details>
<details>
<summary>
R13：Wang, Wong and Xia (2008)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>Qian Wang, T. J. Wong, Lijun Xia.</strong> <em>State ownership, the institutional environment, and auditor choice: Evidence from China</em>. Journal of Accounting and Economics 46(1), 112–134，正式2008；T. J.保持发表记录写法，不猜扩全名。<a href="https://research.cuhk.edu.hk/en/publications/state-ownership-the-institutional-environment-and-auditor-choice--2/">作者机构记录</a>。搜索词：<code>"State ownership, the institutional environment, and auditor choice" "Qian Wang"</code>。</p>
<p>本地原文核对件；PDF4—8/表3—4样本变量模型，PDF21刊页132因果限制及稳健性；附件显示article-in-press，但具有相应期刊分页。</p>
<p><strong>数据与样本。</strong> 纯A上市公司1993—2003，初始8,627删B/H1,205、当地无事务所112、产权缺失1,483、财务信息不足68，剩5,759。审计身份/意见/收费手工来自年报或三大证券报年报摘要，CSMAR主要提供财务；费用只在2001—2003可得。2001起控制权来自年报，早期按2001最终控制人回溯，遇控制权变化另核历史年报。NERI基准用2000年信用市场、政府分权、法律环境指标，并非每年滚动观察。乡镇/村集体归类须遵原文，不应由项目二元SOE替代央地控制分类。</p>
<p><strong>Y构造。</strong> Small local auditor=非全国Top10（年度上市客户资产排名）且与客户同省。合并事务所继承原所和新所登记省份的本地身份；不是“其他所=small local”。核心Y是选择，并不是报表质量。</p>
<p><strong>模型、变量与标准误。</strong> 基准Logit以地方/中央SOE、制度指标及交互解释small-local选择，控制增长、股权发行、规模、ROA、负债率、流动比率、AR/A、INV/A等，年与行业虚拟变量。Growth是下一年收入/本年收入−1；股权发行也涉及未来一年，不能与项目当期growth/financing机械对应。基准只对Growth做1%/99%缩尾；附录对所有财务变量1%或2%处理。PDF7说明除表5转换模型外，Logit/OLS使用Newey–West一阶滞后；稳健性另加按年聚类及Fama–MacBeth年度估计，不能统一写为公司聚类。表5转换模型SE未在本轮确认，标记未核实。</p>
<p>审计所转换为ordered结果：small local转其他、未变/同类内变、其他转small local；产权转换辅助检验也可能内生。PDF21明确指出所有权与审计师选择内生，不可由基准推因果，产权转换也非天然外生。</p>
</details>
<details>
<summary>
R18：Lisic, Silveri, Song and Wang (2015)｜中文逐篇说明、原文定位与检索词
</summary>
<p>Ling Lei Lisic、Sabatino (Dino) Silveri、Yanheng Song、Kun Wang，<em>Accounting fraud, auditing, and the role of government sanctions in China</em>，<strong>Journal of Business Research 68(6):1186–1195</strong>。本地为2013年10月工作稿，以下方法细节来自该稿，不把草稿样本/系数标为正式版数值。<a href="https://digitalcommons.memphis.edu/facpubs/11504/">正式作者机构登记</a>，<a href="https://doi.org/10.1016/j.jbusres.2014.11.013">DOI</a>，<a href="https://ssrn.com/abstract=2402330">工作稿</a>。检索：<code>"Accounting fraud, auditing, and the role of government sanctions in China" Lisic Silveri Song Wang</code>。</p>
<ul>
<li>总体/数据；中国非金融上市公司，1999–2005舞弊发生年度；CSMAR监管舞弊、财务/审计资料；精确回归N本轮未重核</li>
<li>大所定义；每年上市客户总资产规模排名Top10及所规模连续指标；不是四大，也不是本项目本土八大固定分类</li>
<li>Y；会计舞弊及严重度/收入舞弊；发生年对准报告，不以处罚年代替；行业政府监管是情境/异质性</li>
<li>选择尝试；根据已有审计选择模型估计Top10选择，构造IMR加入舞弊回归；第一阶段完整变量、函数形式及可验证排除限制未充分表列，不能反推一个有效IV</li>
<li>其他检验；剔除跨境上市、替代舞弊指标、严重度、收入舞弊、治理控制、受监管行业比较</li>
<li>FE-SE/控制；完整第一阶段、逐列结果控制、FE/聚类本轮未确认；不能从相似美国文献借用清单</li>
<li>定位；本地2013稿的研究设计、自我选择稳健性、舞弊分类和治理控制段；正式版需另作逐表版本对照</li>
</ul>
<p>政府惩罚有助于解释大型所激励，但不是本文已建立的随机惩罚工具变量。项目可借用严重失败代理与供给激励讨论，不把Top10结果直接称Big4效应，也不把IMR当识别已经完成。</p>
</details>
</section>
<section class="level3" id="组织变化与同一客户的处理比较">
<h3 class="anchored" data-anchor-id="组织变化与同一客户的处理比较">1.5 组织变化与同一客户的处理比较</h3>
<p><strong>A．文献的数据与方法</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>国家、资料与样本</th>
<th>结果及测量时点</th>
<th>选择处理、模型与推断</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R07：Jiang、Wang、Wang (2019)</td>
<td>美国公众客户，20次 Big N 收购非 Big N（1976—1995），331家处理客户；会计窗口1974—2000。收购名录与公开财务，不是主动换所。</td>
<td>收购前后 DA 与报表偏差；年度盈余 ERC、收购公告 CAR 是另两套设计。ERC样本8,749公司年度。</td>
<td>质量 DID：前后各五年、排除事件年，公司/年份固定效应、公司聚类；前五年得分1:5无放回匹配。收购 IV 只用于质量，不用于 ERC。ERC附录列年份及消息×年份效应，未列公司效应，标准误未说明。</td>
</tr>
<tr class="even">
<td>R08：Che、Hope、Langli (2020)</td>
<td>挪威私人有限责任公司，2004—2012；合伙人迁移2005—2012。税务/监管ID、Experian/Eniro/BI财务和付款违约。68名可用迁移合伙人、31,418客户年度。</td>
<td>持续经营准确性、年报后12个月违约、意见、负的业绩调整应计绝对值、费用；各结果N不同。</td>
<td>同客户—合伙人跨入四大。年份/行业/合伙人固定效应，非客户效应；OLS/Logit公司聚类、15项风险/复杂度控制。匹配 DID 最近邻、无放回，卡尺0.2量纲未充分核实；另有非四大迁移/安慰剂。</td>
</tr>
</tbody>
</table>
<p><strong>B．项目对应与差别</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>我们已实施的比较</th>
<th>定义与设计差别</th>
<th>当前状态及识别缺口</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R07：Jiang、Wang、Wang (2019)</td>
<td>已有普通换入/换出 DID、九项进入前匹配 DID；组织事件覆盖目前为描述诊断。</td>
<td>普通采用不等于继承收购处理；没有实施收购工具或 Hou 模型预测。不能把质量模型的固定效应/标准误套给 ERC 附录。</td>
<td>作为准实验比较基准，非项目已完成识别策略；接受稿中的样本计数不一致保留说明。</td>
</tr>
<tr class="even">
<td>R08：Che、Hope、Langli (2020)</td>
<td>已检查客户—审计师ID连续覆盖：37次四大进入至少保留一名已验证签字人；未新估计平台效应。</td>
<td>中国上市客户及两名签字人与挪威私人客户—合伙人不同；同ID保留未解决覆盖、存续及同期客户变化。</td>
<td>仅完成可行性诊断；不能提升为已估计的 Che 式处理效应，也不由此新增人员机制方案。</td>
</tr>
</tbody>
</table>
<details>
<summary>
R07：Jiang, Wang and Wang (2019)｜中文逐篇说明、原文定位与检索词
</summary>
<p>John (Xuefeng) Jiang、Isabel Yanyan Wang、K. Philip Wang，<em>Big N Auditors and Audit Quality: New Evidence from Quasi-Experiments</em>，<strong>The Accounting Review 94(1):205–227</strong>。本地为2018年3月接受稿，以下页序按附件；正式书目按2019。<a href="https://doi.org/10.2308/accr-52106">正式出版登记</a>，<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3139642">接受稿登记</a>。检索：<code>"Big N Auditors and Audit Quality" Jiang Wang Wang</code>。</p>
<ul>
<li>国家/事件/来源；美国上市公司；Who Audits America、Public Accounting Report、Audit Analytics寻找1976–2014收购，Compustat财务、LexisNexis公告。最终主事件20次、1976–1995，331个转入Big N客户</li>
<li>Y；有符号/绝对应计残差；FSD财报数值首位数字偏离Benford分布。另研究市场类结果，不应把其财报证据外推为所有市场指标都改善</li>
<li>处理与窗口；原非Big N所被Big N收购且客户转入；主−5至−1、+1至+5，排除0；另±3、含0、全期敏感性</li>
<li>对照/FE/SE；与始终非Big N、始终Big N等比较，另PSM对照及非Big N收购非Big N的安慰剂；公司/年FE、公司聚类</li>
<li>控制；log资产、滞后ROA、滞后杠杆、滞后流动比率、围绕当年的五年现金流波动；后一变量不是纯事前信息，复制时需保留其时间定义并说明</li>
<li>样本N；331是处理客户数，不是回归行数。Table 7 FSD不同对照设定N为23,144、23,182、114,130；不可拼成统一样本</li>
<li>IV；附录Table A3：Acquisition指被收购客户的收购后状态；正文2SLS定义为处理客户收购后五年取1，其他取0。第一阶段BigN~Acquisition＋控制，第二阶段以预测BigN解释质量；样本为1974–2000曾用非Big N的Compustat公司</li>
<li>定位；接受稿研究设计、主结果/稳健性；PDF p.25的2SLS说明、PDF p.49 Table A3。正文五年范围比表注“收购后时期”更明确，不能忽略</li>
</ul>
<p>收购使客户进入大所不完全出于主动择所，因此比常规换所更强；但被收购所本身、人员保留、客户是否继续委托仍可能选择。原文约96%受影响客户转入大所，也不意味着剩余选择为零。IV还需无并购直接效应与无其他同步变化，强第一阶段不证明排除限制。</p>
<p><strong>同一论文的市场设计：质量 DID、盈余 ERC、收购公告 CAR 分开。</strong></p>
<p>Online Appendix A6 PanelC，<strong>Online p.9 / PDF页55</strong>：</p>
<p>[ CAR_{it}=a+b_1S_{it}+b_2Treat_i+b_3S_{it}Treat_i+ b_4BigN_{it}+b_5S_{it}BigN_{it}+YearFE_t+S_{it},YearFE_t+e_{it}. ]</p>
<p>CAR为年度盈余公告中心三日[-1,+1]单因子市场模型异常收益之和；alpha/beta用250日、截至公告前10日估计。S=(实际EPS−预期EPS)/财年末股价；预期EPS引用Hou等(2012)模型方法，<strong>不是I/B/E/S一致预测</strong>。所读接受稿未展开该引用方法的完整EPS预测方程、滚动估计和样本处理，不能替它补造；不新扩展Hou文章任务。稿中未明确给市场收益数据库/指数产品和这一面板最低估计日数；不能凭美国研究惯例自动填成CRSP等权。</p>
<p>Treat定义处理公司；BigN=处理且post，因此b5衡量处理组相对对照的<strong>消息斜率</strong>在收购后是否变。ERC式明确含年度FE及S×年度FE，<strong>未列公司FE</strong>；不要套用主质量DID的公司FE。A6该面板没有明确写SE的聚类口径；主表和其他附录明确公司聚类，但本稿不据此填补此面板未写细节。</p>
<p>BigN收购ERC N=8,749；b5=−.026，t=−1.33，不显著。非BigN M&amp;A对照类检验N=8,336，S×NonBigN M&amp;A=.008，t=.30。稿p.26将ERC和隐含资本成本列为感知类指标，未发现显著改善。它支持“主报表质量改善未必同时在感知指标中检出”，不是所有四大客户的ERC都无差异，也不是已证明市场不在乎审计。</p>
<p><strong>5.4 市场检验二：收购公告事件收益</strong></p>
<p>稿pp.23–24；Online A7，<strong>Online p.11 / PDF页57</strong>。从LexisNexis、Factiva、Google/新闻找到9事件公告日，覆盖236处理公司（331的71%）；用首次公开谈判新闻日替代时结论相同。模型同为250日截至公告前−10日的单因子市场模型，但事件是<strong>事务所收购公告</strong>，不是年报或审计意见签署日，不包含S。</p>
<ul>
<li>[0,+1]；236；−.26%；−.66；−.31</li>
<li>[-1,+1]；236；−.54%；−1.00；−.31</li>
<li>[-2,+2]；236；−.17%；−.68；−.18</li>
<li>[-3,+3]；236；−.67%；−.68；−.31</li>
</ul>
<p>作者把此项解释为改善审计质量与更高费用等成本的净效应；样本时期审计费未公开，因此不是实际费用分解。Table7在此接受稿是规模分类的主质量分析，<strong>市场公告检验位置是Online A7</strong>，不要照现有主报告书目备注误引Table7。</p>
</details>
<details>
<summary>
R08：Che, Hope and Langli (2020)｜中文逐篇说明、原文定位与检索词
</summary>
<p>Limei Che、Ole-Kristian Hope、John Christian Langli，<em>How Big-4 Firms Improve Audit Quality</em>，<strong>Management Science 66(10):4552–4572</strong>，正式版。<a href="https://pubsonline.informs.org/doi/10.1287/mnsc.2019.3370">出版商</a>。检索：<code>"How Big-4 Firms Improve Audit Quality" Che Hope Langli</code>。</p>
<ul>
<li>国家/客户/期间；挪威私人有限责任公司，2004–2012，人员转入2005–2012；不是上市公司样本，也不是只观察两个签字位次的中国面板</li>
<li>数据与身份；税务资料姓名与金融监管局执业人员名册人工匹配，约72%全部LLC可识别；Experian AS/Eniro AS提供所、报告、意见、费用等，BI数据库财务；Experian付款违约记录</li>
<li>样本；77位迁移合伙人，68位满足同客户前后观察/控制要求；总31,418客户年。不同Y：GC准确性31,331、GC31,327、修改意见数31,418、应计质量31,325、费用30,862</li>
<li>Y；GC判断准确性以年报发布后12个月内公开付款违约衡量：正确取1，Type I/II错误取0；不是破产替代。修改意见数；Kothari式−绝对异常应计；审计费</li>
<li>主要比较；同一客户—合伙人组合转入Big4，单列转入年、首个之后年度、其后年度，区分即时与学习过程</li>
<li>FE/估计/SE；Eq.(1)年、行业、合伙人FE；连续Y OLS、二元Y logit，公司聚类Huber–White。不要把主规格改写成客户FE</li>
<li>控制清单；ln资产、ln员工、ln年龄、行业数量、存货＋应收/资产、无形资产/资产、杠杆、杠杆变化、破产概率、ROA、销售增长、现金流、亏损、短期投资/资产、流动比率；个别Y有相应改式，按原表注确认</li>
<li>匹配DID；§5.1/Table 10：迁移且同配对客户对未迁移的非Big4客户—合伙人组合；全部Eq.(1)控制入logit、最近邻无放回、卡尺0.2；均值、t、标准化偏差、L1检查。卡尺量纲本轮未再确认，不写成0.2原始得分或0.2SD的既定事实</li>
<li>选择/反向因果检验；非Big4→非Big4迁移安慰剂，合并子样本，跟随/未跟随客户；客户ROA/杠杆/增长/亏损、国外业务与上市需求等变化检验</li>
<li>定位；正式研究设计§3，PDF p.8控制；§5.1/Table 10、§5.4–5.7/Table 12，正式pp.4566–4568</li>
</ul>
<p>保持客户和人员身份能削弱“客户不同”“四大招到更好人”这两种解释。仍须考虑谁被招入、哪些客户跟随、同步需求变化；财务健康未显著改善也不能证明任何潜在混杂都不存在。该文的时序和安慰剂是机制辨别证据，不是完全随机指派。</p>
</details>
</section>
<section class="level3" id="选择模型与工具变量的适用条件">
<h3 class="anchored" data-anchor-id="选择模型与工具变量的适用条件">1.6 选择模型与工具变量的适用条件</h3>
<p><strong>A．文献的数据与方法</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>国家、资料与样本</th>
<th>结果及测量时点</th>
<th>选择处理、模型与推断</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R14：Larcker、Rusticus (2010)</td>
<td>工具变量方法分析；细节核读2004年11月工作稿，正式2010书目已核实。没有独立四大客户国家样本或项目N。</td>
<td>在工具强度、内生性、排除限制不完全成立时，比较 IV 与 OLS 的偏差、方差和可靠性。</td>
<td>第一阶段强度/偏R²与排除有效性不同；弱工具或轻微内生工具可使估计更不可靠。不是通用中国审计师工具来源。</td>
</tr>
<tr class="even">
<td>R15：Lennox、Francis、Wang (2012)</td>
<td>选择模型的方法综述，含75项会计研究；不是独立四大客户总体。</td>
<td>区分样本选择（只在入选者中观测结果）与内生处理（两类审计师客户均观测结果）。</td>
<td>需要排除限制、分布/函数形式假设及敏感性分析。单侧 IMR 不自动适用于全样本四大/非四大处理比较；IMR显著不证明因果。</td>
</tr>
</tbody>
</table>
<p><strong>B．项目对应与差别</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>我们已实施的比较</th>
<th>定义与设计差别</th>
<th>当前状态及识别缺口</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R14：Larcker、Rusticus (2010)</td>
<td>本章没有已验证的四大选择 IV；供给/收购覆盖属于独立描述工作。</td>
<td>分所、合并或市场份额可能直接影响结果；第一阶段非零不证明排除限制。</td>
<td>仅用于适用条件约束；不新增 IV 模型或工具。</td>
</tr>
<tr class="even">
<td>R15：Lennox、Francis、Wang (2012)</td>
<td>两类客户均观测失败结果；控制、PSM、DID是明确比较，不是 Heckman 修正。</td>
<td>两组结果均可见的审计师选择，不只是结果缺失的样本选择；目前没有已辩护的排除条件或核实的 IMR 实施。</td>
<td>用于解释边界；未新估计选择模型，也不称其已经解决识别缺口。</td>
</tr>
</tbody>
</table>
<details>
<summary>
R14：Larcker and Rusticus (2010)｜中文逐篇说明、原文定位与检索词
</summary>
<p>David F. Larcker、Tjomme O. Rusticus，<em>On the use of instrumental variables in accounting research</em>，<strong>Journal of Accounting and Economics 49(3):186–205</strong>。本地为2004-11-29工作稿，方法定位按该稿§3/§6；不能将工作稿调查样本或段落编号当正式版。<a href="https://doi.org/10.1016/j.jacceco.2009.11.004">正式出版登记</a>。检索：<code>"On the use of instrumental variables in accounting research" Larcker Rusticus</code>。</p>
<ul>
<li>类型；IV方法研究，不是Big4客户样本；没有提供一枚已验证适用于中国Big4聘用的Z</li>
<li>相关性；关注排除工具联合强度、partial R²与弱工具；工具很多或第一阶段某项显著不够</li>
<li>外生性；允许轻度内生的工具即可使IV偏误很大；强第一阶段也不解决Z直接作用于Y</li>
<li>比较对象；IV的偏误/方差相对于OLS是否改善，需要工具与误差相关性、强度等条件，不能因使用2SLS就升格证据</li>
<li>项目应用；分所进入、距离、地区四大份额、SOE、人员流动、竞争合并若作为Z，各自写清直接路径；前述几篇不能替本项目证明排除限制</li>
<li>定位；本地工作稿§3、§6；正式版书目实时核对，未重做工作稿到正式版全篇版本比对</li>
</ul>
</details>
<details>
<summary>
R15：Lennox, Francis and Wang (2012)｜中文逐篇说明、原文定位与检索词
</summary>
<p>Clive S. Lennox、Jere R. Francis、Zitian Wang，<em>Selection Models in Accounting Research</em>，<strong>The Accounting Review 87(2):589–616</strong>，正式版。<a href="https://publications.aaahq.org/accounting-review/article/87/2/589/3388/Selection-Models-in-Accounting-Research">出版商</a>，<a href="https://doi.org/10.2308/accr-10195">出版登记</a>。检索：<code>"Selection Models in Accounting Research" Lennox Francis Wang</code>。</p>
<ul>
<li>证据类型/样本；方法研究，审查75篇会计文章；不是一个国家Big4客户的审计结果样本，没有可套用的财报Y或客户N</li>
<li>两类问题；结果只在选中子样本可见的sample selection，与全样本可见Y但D内生的treatment selection不同；Big4/非Big4通常更接近后者，不直接套用只用于D=1样本的单边IMR</li>
<li>排除限制；第一阶段影响选择、却不直接影响结果的变量需经济解释；只有非线性函数形式也能参数识别，但结论依赖分布/规格，不能因此声称获得可信外生性</li>
<li>模型诊断；第一阶段规格、共线性、排除限制与结果敏感性；IMR不显著不是“没有选择”，显著也不是“修正后处理因果”</li>
<li>原文定位；正式pp.591–593及§VI–VII，pp.610–612；方法批评和实施建议</li>
</ul>
<p>对参数化内生二元处理，示意（不是本轮已执行模型）为：</p>
<p>[ D_i=1{W_i+v_i&gt;0}, Y_i=X_i+D_i+u_i. ]</p>
<p>在相应正态设定下，全样本的选择修正项形式为</p>
<p>[ _i=D_i -(1-D_i). ]</p>
<p>该表达只说明为何两边选择不同，不表示任何logit预测概率均可直接塞入正态IMR。R03原文logistic＋IMR的复现问题应明确保留。项目未找到并批准可信排除限制前，不新增“以函数形式解决选择”的主因果模型。</p>
</details>
</section>
<section class="level3" id="连续盈利消息与市场反应">
<h3 class="anchored" data-anchor-id="连续盈利消息与市场反应">1.7 连续盈利消息与市场反应</h3>
<p><strong>A．文献的数据与方法</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>国家、资料与样本</th>
<th>结果及测量时点</th>
<th>选择处理、模型与推断</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R01：Teoh、Wong (1993)</td>
<td>美国 NYSE/AMEX/NASDAQ，1980—1989；Compustat/CRSP/I/B/E/S。行业—资产匹配1,282公司年度对，控制缺失前潜在2,564条；换所134事件。</td>
<td>意外 EPS 按预测日股价缩放；从预测日到公告日累积对数市场调整收益，窗口长度可变；CAR2用预测日前市场模型。</td>
<td>非 Big 8 向 Big 8 同财年/SIC、最近资产匹配。合并 ERC 含消息与中位数二分 MB、beta、对数规模、分析师人数倒数的交互。无公司/年份固定效应；匹配 CAR1 用 White，其余 OLS t，未报告公司聚类。</td>
</tr>
<tr class="even">
<td>R03：Du、Zhou (2014)</td>
<td>中国 CSMAR：正文1995—2012、表从1996起；20,662公司年度，其中 Big 5 1,285。美国1983—2012，38,206；不能混用中美N。</td>
<td>中国意外盈余用盈余变动；正文以股价、变量表以账面权益为分母，存在不一致。三日 CAR；市场模型印刷符号也不一致。</td>
<td>年份/行业固定效应，非公司效应；稳健t未确认公司聚类。完整/简化 ERC 交互；选择 Logit+IMR中国N=10,139，不是2SLS或共同样本修正比较；IMR公式未完整说明。</td>
</tr>
<tr class="odd">
<td>R25：Francis、Ke (2006)</td>
<td>美国2001年首次非审计服务费披露；1999—2002季度公告，各披露日前后一年。EDGAR/费用、I/B/E/S、Compustat/CRSP。3,133公司、16,910公司季度；Cook筛后主N=16,243。</td>
<td>[-1,+1] CAR 相对规模十分位基准，乘100；实际季度EPS减一致预测、按股价缩放。高 NAS 同时要求金额高及费用份额高。</td>
<td>披露后×消息×高NAS的ERC比较；盈余/风险/规模/行业斜率控制，公司聚类。无公司固定效应、普通PSM或IV。首次费用披露与季度盈余日期不同。</td>
</tr>
</tbody>
</table>
<p><strong>B．项目对应与差别</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>我们已实施的比较</th>
<th>定义与设计差别</th>
<th>当前状态及识别缺口</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R01：Teoh、Wong (1993)</td>
<td>已估计年度 CAR 和日度路径的连续消息×事务所交互，报告非线性斜率与固定消息差。</td>
<td>消息按预测值缩放、固定公告窗及A股市场基准均不同；未精确复制行业—资产匹配、二分控制或换所 ERC。</td>
<td>已实施相关 ERC 比较；斜率差不能独自分开现金流消息、可信度与时变客户选择。</td>
</tr>
<tr class="even">
<td>R03：Du、Zhou (2014)</td>
<td>已有四大/本土八大/Other的预测消息交互、多种 CAR 窗口及公开信息检查。</td>
<td>消息分母、审计师历史、市场权重、窗口、协变量不同；固定三分类并非历史 Big 5。</td>
<td>作为中国 ERC 对照，保留原文定义疑点；不能由该文证明本项目的因果品牌效应。</td>
</tr>
<tr class="odd">
<td>R25：Francis、Ke (2006)</td>
<td>已有公告 CAR 与连续消息—类别交互，图区分斜率与水平差。</td>
<td>没有首次 NAS 披露季度面板或费用份额处理；年度事务所类别差异不是 NAS 披露效应。</td>
<td>仅比较消息交互结构；未复制披露冲击和原文配对稳健性。</td>
</tr>
</tbody>
</table>
<details>
<summary>
R01：Teoh and Wong (1993)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>完整书目</strong>：Siew Hong Teoh；T. J. Wong. <em>Perceived Auditor Quality and the Earnings Response Coefficient</em>. The Accounting Review 68(2):346–366，1993年4月，正式发表。保留发表名 T. J. Wong，不推测展开姓名。</p>
<p><strong>原文与实时核验</strong>：<a href="https://bpb-us-e2.wpmucdn.com/sites.uci.edu/dist/e/360/files/2012/08/Perceived-Auditor-Quality-and-the-Earnings-Response-Coefficient.pdf">作者公开同版全文</a>；<a href="https://www.jstor.org/stable/248405">JSTOR出版记录</a>。本轮作者全文下载为 本地原文核对件，2,883,513字节、22页，包含一页JSTOR封面，PDF页2对应印刷p.346。Zotero附件 本地原文核对件 为2,779,868字节。搜索词：<code>"Perceived Auditor Quality and the Earnings Response Coefficient" "Teoh" "Wong"</code>。</p>
<p><strong>2.1 数据与样本</strong></p>
<ul>
<li>覆盖；1990 Compustat annual industrial tape的PST、full coverage、research files；NYSE、AMEX、NASDAQ；年度盈余，作者明确选择年报因为要求外部审计；pp.351–352，fn.9</li>
<li>初始公司年；PST 12,940；FCI 10,465；research 4,579。主样本1980–1989；research可用1981–1988，并排除删除前3年以降低退市等情形的影响；pp.351–352</li>
<li>预测可用；I/B/E/S跟踪且最新一致预测距年度盈余公告不超过200交易日：PST 9,624、FCI 5,215、research 2,604；p.352</li>
<li>收益可用；预测日至公告日须有CRSP日收益：PST 9,264、FCI 4,998、research 2,513。其后作者报告Big8 15,480、非Big8 1,297；逐文件和与审计师组和相差2例，不能替作者重构未提供的去重过程；p.352</li>
<li>匹配；先要求行业有两种客户；每个非Big8客户匹配同财年、同四位SIC、资产最近的Big8客户，必要时退到三位/两位SIC；没有公布PSM模型或一般caliper；p.352</li>
<li>异常UE；删除 (UE&gt;1)；pp.352、356</li>
<li>最终匹配；四位SIC 1,263对、三位4对、两位15对，共1,282公司年对，即2,564条潜在公司年记录；不是1,282家唯一公司。原文后续说明控制缺失另去约2%，不能把2,564称为每个最终模型N；p.352；p.359 fn.21</li>
<li>换所来源；1977–1985 Who Audits America；1973–1976 Disclosure；补Compustat的1985–1988变更；p.353</li>
<li>换所筛选；前后各两年财务/CRSP可用；非子公司；前两年和后两年分别保留同一审计师；预测I/B/E/S可用，1976以前15事件补Value Line；p.353</li>
<li>最终换所；134事件：非Big8→Big8 114、反向20；1973–1988。前后各两年估计，控制缺失另去约3%；134不是回归公司年数；Table1，p.353；Table4注，p.362；fn.21</li>
</ul>
<p>原文没有可复用的完整证券代码清单、匹配权重/是否重复用同一Big8匹配者的程序或逐条连接代码。本稿不补造。匹配依客户资产，回归规模控制则用年初市值，二者要区分。</p>
<p><strong>2.2 消息与Y的构造</strong></p>
<p>[ UE_{it}=, CAR1_{it}=<em>{d=IB}^{ED}(1+R</em>{id}-R_{md}). ]</p>
<p>IB是一致预测日、ED是年度盈余公告日；股价缺失改用财年末股价。I/B/E/S每月第三个周四更新中位数一致预测：公告在该日之后则取本月，否则取上月，最大预测提前200交易日；100日上限为敏感性分析。实际EPS及公告日期来自Wall Street Journal Index。CAR从<strong>预测日到公告日</strong>累计，不能改写为统一三日CAR。匹配样本累计窗平均Big8 28.80日、非Big8 29.21日；中位数18与16日；换所样本均值27.65与30.98日（Table2，p.354）。</p>
<p>市场收益：NYSE/AMEX用CRSP等权指数，NASDAQ用NASDAQ市场指数。CAR2对同一累计窗累加单因子市场模型异常收益的log；alpha/beta用<strong>预测日前360日</strong>估计，至少100个日收益（pp.357–358）。扫描式需按原图理解残差符号，不用Du–Zhou印刷错误倒推此式。</p>
<p><strong>2.3 模型、选择处理与推断</strong></p>
<p>原文式(6)，用D=1表示<strong>非Big8</strong>：</p>
<p>[ CAR=a_0+a_1D+a_2UE+a_3UE,D+ _{z{MB,,LMV,1/N}}(c_zUE,z+d_zUE,z,D)+e. ]</p>
<p>MB为年初市值/账面权益；beta来自市场模型；LMV为年初市值对数；N是一致预测的分析师人数。实际回归将MB、beta、LMV和1/N各转为“高于中位数”的0/1变量（p.359），不是直接使用连续控制。没有直接时间序列盈余持续性估计：作者解释过长的年报历史要求会大量丢样本（p.358 fn.18）。给定z的非Big8−Big8斜率差为 (a_3+d_zz)；a3是控制指标全为0的残余差。</p>
<p>行业资产匹配调整可观测客户差异；换所样本利用同一公司的前后观测，但依然是上述pooled OLS，不是公司FE、外生事件DID或IV。原文没有PSM、IMR。Table4报告常规OLS t；匹配CAR1因异方差另报White z（p.362），没有说明公司聚类。不要把现代聚类规则套给旧文。</p>
<p><strong>方向与结果</strong>：匹配CAR1的UE×D=−.401，White z=−1.972，表中双侧p=.0486；CAR2=−.317，t=−1.776，双侧p=.0759，正文按事前单侧预测称5%显著。换所CAR1=−.974，t=−4.290；CAR2=−1.015，t=−3.874（Tables4、pp.361–363）。Table4注却把D写成Big8=1，与式(6)定义、正文预测及负系数解释不一致；本稿按正文定义解释，并保留该印刷冲突。</p>
<p><strong>识别边界</strong>：p.350模型 (ERC=v/(v+)) 同时取决于事前基础价值不确定性v及消息噪声eta；结论是审计师规模/可信度和信息精度模型的联合证据。作者在p.365明确承认未控制的ERC决定因素及组间差异化测量误差会造成偏差。同公司比较不能自动排除换所前财务改善或时变选择。</p>
</details>
<details>
<summary>
R03：Du and Zhou (2014)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>完整书目</strong>：Jun Du；Gaoguang Zhou. <em>Big N Auditors and Earnings Response Coefficients – A Comparison Study between the US and China</em>. China Accounting and Finance Review 16(2):183–201，2014，正式发表，DOI 10.7603/s40570-014-0014-2。<a href="https://scholars.hkbu.edu.hk/en/publications/big-n-auditors-and-earnings-response-coefficients-a-comparison-st/">作者机构登记</a>本轮核实；<a href="https://www.polyu.edu.hk/af/-/media/department/af/list-of-issues/11_du_and_zhou.pdf?hash=FC7B895C82C90AB8992F07D817CC13E1&amp;rev=26a99d7a4ff04b3296f2bf9b02f18f7c">期刊机构公开全文</a>。本轮方法读取 本地原文核对件，506,578字节、19页，PDF页1对应印刷183。搜索词：<code>"Big N Auditors and Earnings Response Coefficients" "Du" "Zhou"</code>。</p>
<p><strong>3.1 中国样本的可追踪流程</strong></p>
<ul>
<li>1；从CSMAR取1995–2012上市公司；1995起能识别国际Big5；未给具体CSMAR子库/表/字段编号、下载日期或版本；年表实际第一年1996</li>
<li>2；要求市值、财务报表、日度价格可计算CAR；排除金融业；没有初始N与各步删除数；没给ST、退市、IPO年、A/B/H股等额外筛选的明确规则，不得自行加上</li>
<li>3；国际Big5包括Andersen、PwC、Deloitte、EY、KPMG；国内Top10及国内Big5按每年审计客户资产总额排名；未列逐年客户证券名单或完整大所排行；不能用现代固定Local8代替</li>
<li>4；最终20,662公司年：Big5 1,285、其他19,377；Big5占6.22%公司年和43.25%合计客户资产；不是20,662唯一公司；未提供逐字段缺失连接、重复财报处理、审计所更名谱系规则</li>
<li>5；中国结果段写连续变量在“5% level”缩尾；没有充分明确全样本还是逐年、是否双尾及对每个变量的执行；不能直接移用美国上下1%规则</li>
<li>6；完整/简化ERC回归；Table9另加选择校正；Table9降至10,139，未给逐步减少10,523例的解释；不能把显著性变化全部归于IMR</li>
</ul>
<p>来源：pp.186–190、194–199。年表Table1B（p.189）的非Big5/Big5公司年数为：1996 286/20；1997 483/27；1998 688/28；1999 785/33；2000 873/38；2001 991/50；2002 1045/69；2003 1062/110；2004 1114/102；2005 1198/89；2006 1180/90；2007 1222/91；2008 1332/96；2009 1409/96；2010 1498/95；2011 1824/111；2012 2107/125。这是可核查的年度覆盖，不是具体企业代码清单。</p>
<p><strong>3.2 Y、消息、行情与控制</strong></p>
<ul>
<li>CAR1；CSMAR公司日收益减CSMAR等权市场收益；公告附近三日累加 ((1+R_i-R_m))；p.186、Table2；正文仅写around，不像估计窗那样给明确整数端点，不擅自当作者代码指定[-1,+1]</li>
<li>CAR2；单因子市场模型；公告前−256至−7日估计，至少100日；p.187；印刷式为 ((1+R_i-_i+_iR_m))，beta前为加号，与标准残差不同；需作者代码/勘误确认</li>
<li>UE2；中国无充分分析师资料，以当年earnings减上年earnings代替意外盈余；p.187写除公告前一日股价，缺失用年末价；Table2 p.190写除账面权益；earnings为总利润还是EPS未在此处明确，不替作者决定</li>
<li>MB；市值/账面权益，成长及持续性proxy；p.187</li>
<li>BETA；上述市场模型收益斜率，风险proxy；p.187</li>
<li>LMV；客户市值自然对数；p.187</li>
<li>1/N；分析师人数倒数；美国用，中国不纳入；p.187</li>
<li>年报消息；年度盈余公告，与财报及审计师按公司年连接；未给公告字段、延期公告、非交易日或收盘后公告的完整映射规则</li>
</ul>
<p>中国消息变量只能按原文写为两个未统一版本：</p>
<p>[ UE2^{text}<em>{it}=, UE2^{Table2}</em>{it}=. ]</p>
<p>前者股价缺失采用财年末价；第二个只是Table2明示的另一种缩放。不能把它们拼成一种合法且已确认的实现。正文在中国另试300日窗口未得到Big5 ERC更高的证据，并提出业绩预告可能提前反映信息的解释（p.186 fn.2）；这是作者的可能解释，不是已经识别的渠道。</p>
<p><strong>3.3 ERC模型与选择方程</strong></p>
<p>中国完整式：</p>
<p>[ CAR=a_0+a_1UE+a_2B5+a_3UE,B5 +_{z{MB,BETA,LMV}}(c_zUE,z+d_zUE,z,B5) +YearFE+IndustryFE+e. ]</p>
<p>完整式给定X的斜率差为 (a_3+d_zz)。p.196因部分VIF超过500、二重与三重交互相关接近1，另删除所有三重交互；不能将简化式的a3与完整式的a3看作同一平均对象。年和行业FE分别列入，不是行业×年，也未列公司FE。表注报告robust t，没有明确公司聚类和两阶段重抽样规则。</p>
<p>第一阶段选择logit的九项变量及其定义（pp.198–199）：</p>
<p>[ (B5=1Z)=(b_0+b_1SIZE+b_2GROWTH+b_3ROA+b_4LEVERAGE+ b_5CACL+b_6OTHREC+b_7INVENTORY+b_8SOE+b_9LARGEHOLDING). ]</p>
<p>SIZE=ln资产；GROWTH=销售收入年度增长；ROA=净利/资产；LEVERAGE=负债/资产；CACL=流动资产/流动负债；OTHREC=其他应收/资产；INVENTORY=年末存货/资产；SOE=国企；LARGEHOLDING=第一大股东持股。作者将生成的IMR放入第二阶段ERC，不是用预测B5替换实际B5的工具变量2SLS。Table9称“Heckman’s two-stage least square”，但正文第一步明确是logit、第二步加IMR。IMR从logit构造的确切式、排除变量的经济论证及有效排除限制没有完整给出；不能将名称当作已消除未观测选择或反向因果的证据。</p>
<ul>
<li>Table7A完整交互，全样本；UE×Big5：CAR1 .758(t=1.01)、CAR2 .324(t=.42)；单项不显著，且三重交互使其不是平均ERC差</li>
<li>Table7B删三重交互，全样本；.072(t=1.72)、.090(t=2.10)；简化后有弱/显著差异；后半列标题重复写CAR1，正文对应CAR2，保留疑点</li>
<li>Table7B post-2001；.056(t=1.38)、.073(t=1.75)；不能说两种收益口径均5%显著</li>
<li>Table9 IMR，N=10,139；完整 .251(t=.30)、−.244(t=−.29)；简化 .062(t=1.30)、.074(t=1.53)；不显著；应另在同样10,139样本估计未校正式，才可区分失样与校正影响；原文未完成此分解</li>
</ul>
<p>另有样本冲突：Table7A post-2001 N=16,082，7B为17,126，而总样本和pre-2001未变；未解释。BIG5的若干表注又写成“top5 auditors in China”，而p.187明确列国际Big5；本稿以方法正文定义为准并提示表注不一致。上述原文疑点决定它不是可一键准确复刻的中国四大因果证据。</p>
<p><strong>3.4 美国部分及项目差别</strong></p>
<p>美国正文1983–2012、I/B/E/S预测＋Compustat财务＋CRSP收益，删除少于100日收益、四位SIC行业BigN占100%、模型缺失，上下1%缩尾后38,206公司年（p.187）；摘要却写1984起。美国UE1用实际−一致预测/股价，收益为公告日起300日累计（p.186原文from，未完整列方向及端点），不是中国三日与年度差分消息。对照只能解释不同制度和不同定义下的关联，不能直接作同尺度因果强弱排名。</p>
<p>项目市场基准是滞后一交易日流通市值加权A股收益，非原文等权；项目连续S用券商中位数/绝对预测EPS，非中国UE2；61为三组、共同UE×控制斜率而无审计师三重控制交互；74为日度FE，80为公司/财年FE的年报CAR曲线。项目没有按本篇构造九项logit-IMR并验证其排除限制。R03应在表中标为“已核验原文、方法可参考、公式/样本有待作者确认”，不能用它保证我们的选择已经被排除。</p>
</details>
<details>
<summary>
R25：Francis and Ke (2006)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>完整书目</strong>：Jere R. Francis；Bin Ke. <em>Disclosure of fees paid to auditors and the market valuation of earnings surprises</em>. Review of Accounting Studies 11(4):495–523，2006，正式版，在线2006-11-03。DOI 10.1007/s11142-006-9014-z。<a href="https://link.springer.com/article/10.1007/s11142-006-9014-z">出版商实时核验</a>。本轮读取 本地原文核对件，329,779字节、29页；PDF页1为印刷495。搜索词：<code>"Disclosure of fees paid to auditors and the market valuation of earnings surprises" "Francis" "Ke"</code>。</p>
<p><strong>4.1 样本与事件的严格区分</strong></p>
<p>SEC首次费用披露要求针对2001-02-05起提交的proxy statements；每家公司的<strong>首次实际披露日期</strong>决定Post，不是全样本统一用该法定日期分组（pp.498、501）。季度盈余公告在首次披露前后各一年；2001首次费用来自EDGAR公开proxy，主要由Standard &amp; Poor’s整理、辅以The Emerson Company；季度财务、收益、预测分别需Compustat、CRSP、I/B/E/S可用。最终3,133家公司、16,910公司季：披露前8,559、后8,351，财季结束日落在1999–2002，93%落在2000/2001。不排除金融业或其他行业（pp.505–506）。不是事务所全部客户，也不是只选四大。</p>
<p>主回归再按Cook’s distance删除影响观测，Table3列(1)实际N=16,243，不应把16,910写成主回归N（pp.509、512）。没有给本稿可确认的具体Cook阈值，不能补成4/N或其它规则。另有同公司同财季配对、仅披露前后紧邻两次公告、剔除紧邻两次、仅第四季、排除Enron时期等敏感性分析，不是PSM。</p>
<p><strong>4.2 Y、消息与分组</strong></p>
<p>[ CAR3_{iq}=100<em>{d=-1}<sup>{+1}(R_{id}-R</sup>{size decile}</em>{md}), FERR_{iq}=. ]</p>
<p>收益基准是对应规模十分位内的NYSE/AMEX/NASDAQ价值加权收益，分组使用测试年度1月1日市值；不是简单全市场等权或价值加权指数。Y单位是百分数。五日窗口是敏感性分析。实际EPS来自I/B/E/S；每位分析师取上一季度盈余公告之后、本季度公告之前最近预测再算中位数，60日预测限制为敏感性分析（pp.501–503）。股价分母的原文表述是“fiscal year end stock price for quarter t−1”（正文p.501与Table1注p.508）；这一表述未充分明确为普通上季度末还是另一财年末取价规则，本稿保留 <code>P^{paper}_{q−1}</code>，不自行改成明确代码。</p>
<p>HighNAS=1须<strong>同时</strong>满足非审计费&gt;样本75分位$1,074,000，且非审计费/总费用&gt;中位数.574（pp.502–503）。用首次披露所报告的费用定义前后相同的分组。非审计费是审计客户支付给在任审计师的非审计服务费。它不是Big4 dummy。</p>
<p><strong>4.3 模型、控制、选择与推断</strong></p>
<p>式(5)，p.501：</p>
<p>[ CAR3=a+b_1Post+b_2FERR+b_3Post,FERR+b_4FERR,NAS +b_5Post,FERR,NAS+FERR,X’b_6+e. ]</p>
<p>b5表示高NAS相对低NAS的ERC差在披露后改变多少；b4为披露前的ERC组别差。前后样本有助于调整与NAS相关的不变、未观测ERC因素，但没有完全排除时变差异。主式没有NAS和X的独立主效应，也没有公司或年度FE；作者补入主效应后结论相同（p.502 fn.8）。行业进入<strong>FERR×行业</strong>的斜率交互，只对样本≥1,000公司季的行业允许独立斜率，不应笼统写成“行业固定效应”。Post控制共同前后变化；不是行业×年度FE。</p>
<ul>
<li>GROWTH；当前季度分析师5年长期盈利增长预测中位数（百分比）；成长</li>
<li>STDRET；公告前−7日结束的90日日收益标准差，至少10日；风险/基础现金流不确定性</li>
<li>DE；短期＋长期负债/权益；风险</li>
<li>LNMV；季初普通股市值对数；规模</li>
<li>ABSFERR；绝对FERR；ERC非线性</li>
<li>LOSS；当前季亏损；持续性</li>
<li>RESTRUCTURE；Compustat季度special item #32/资产≤−5%；重组及持续性</li>
<li>FQTR4；第四财季；季度盈余/年度公布性质差别</li>
<li>INDUSTRY；文中采用的行业分组，满足上述N要求；行业消息斜率</li>
</ul>
<p>没有在主规格直接用长时间序列持续性估计，另加为敏感性分析；分析师分歧因25%缺失不纳入主式，补充加入仍保持结论（pp.503–504）。高/低应计分组用季度净利减经营现金流的绝对值/资产，按同季度样本中位数分类（pp.505、508），不是DA。</p>
<p>SE允许异方差和同公司任意相关，即公司聚类，跨公司独立；各模型Cook删除、双侧检验（p.509 fn.17；Table3注p.512）。没有第一阶段选择模型、PSM、IV。主表b5=−156.064、SE39.452，p&lt;.01；b4=64.036、SE35.242，10%显著。因为CAR是百分数、FERR股价缩放，不能与项目绝对预测分母的斜率直接比数值。</p>
<p><strong>原文限制</strong>：p.501 fn.6说明首次费用披露也可能改变对盈利持续性、风险和增长的预期，研究设计难将其完全拆开；p.498 fn.3及pp.520–521承认费用与其他不可观测客户特征相关，感知独立性变化不能证明实际独立性受损。本文较适合说明“新审计师相关信息的披露如何改变消息定价”，不能作为四大审计改善真实报表的直接证据。</p>
</details>
</section>
<section class="level3" id="分析师预测与公告前后信息环境">
<h3 class="anchored" data-anchor-id="分析师预测与公告前后信息环境">1.8 分析师预测与公告前后信息环境</h3>
<p>预测误差、预测分歧与 BKLS 信息性质回答不同问题。现有公告前后更新结果已经估计，但我们的 broker 配对、原始单位与控制规格不同于 He 等的行业—年排名模型；不能称为其完整复现。</p>
<p><strong>A．文献的数据与方法</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>国家、资料与样本</th>
<th>结果及测量时点</th>
<th>选择处理、模型与推断</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F1：Behn、Choi、Kang（2008；R02）</td>
<td>美国有分析师覆盖的上市公司；I/B/E/S、Compustat，1996—2001。准确度9,261公司年度；分歧3,749。未来EPS扩展用到2003，非主审计样本延长。</td>
<td>准确度为实际EPS减平均预测的绝对误差取负，再除上一财年末股价；分歧为预测标准差除同一股价。公告前约两个月至前三日，各分析师最新预测；分歧至少4人。</td>
<td>Big 5及按客户资产平方根计算的所内行业集中度。结果回归+Big 5选择Probit/IMR；选择含规模、资产构成、杠杆、亏损、ROA、债务发行。年份指示、公司聚类稳健标准误；不同结果控制不同。无已核实PSM/CEM；IMR依赖假设，未表列换所比较不是现代DID。</td>
</tr>
<tr class="even">
<td>F2：Barron、Kim、Lim、Stevens（1998）</td>
<td>分析师预测的测量模型；没有独立国家/年份/实证N，也没有审计师处理或客户总体。</td>
<td>用预测方差D、一致预测平方误差SE和人数N：<span class="math inline">\(V=SE+(1-1/N)D\)</span>，<span class="math inline">\(C=SE-D/N\)</span>，<span class="math inline">\(\rho=C/V\)</span>；等私人精度下<span class="math inline">\(h=C/V^2\)</span>、<span class="math inline">\(s=D/V^2\)</span>。</td>
<td>用共同/私人信号假设连接预测矩和信息性质，“私人”不等于内幕信息。没有结果回归固定效应、标准误、匹配或DID/IV。偏差、从众及逐公司年度代入误差影响解释，负h不符合精度含义。</td>
</tr>
<tr class="odd">
<td>F3：He、Sidhu、Taylor（2019）</td>
<td>美国上市公司，1985—2015；I/B/E/S未调整明细、Compustat。主样本25,111公司年度、5,353公司；SOX扩展为1998—2007美国/非美国上市公司，N=13,546。</td>
<td>年t公告前60/后30日，对同一t+1目标的BKLS性质变化，至少2位更新分析师。D/SE按下一年实际EPS绝对值缩放；排除绝对EPS&lt;0.10美元和负h。</td>
<td>Big N与4种行业份额/领先代理；Probit/IMR、最近得分PSM、autocuts CEM、公司效应检查。主变量在行业—年内排名，非吸收该效应；消息、规模、MB、覆盖控制，公司/年份双向聚类。PSM卡尺/放回/匹配N未披露于已核读稿；SOX处理是监管暴露，非四大聘用。</td>
</tr>
</tbody>
</table>
<p><strong>B．项目对应与差别</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
<col style="width: 25%"/>
</colgroup>
<thead>
<tr class="header">
<th>文献</th>
<th>我们已实施的比较</th>
<th>定义与设计差别</th>
<th>当前状态及识别缺口</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F1：Behn、Choi、Kang（2008；R02）</td>
<td>已有 CSMAR 预测、实际EPS、披露日期、价格和事务所类别；公告前后配对更新已估计，设计不同。</td>
<td>项目配对同broker，前60/后30日，固定下一年盈余；原文是公告前准确度/分歧、个体分析师、上年末股价分母及4人限制。</td>
<td>精确原文窗口/结果、行业集中度与完整Probit/IMR尚未核实为已完成；字段可得不等于已经实施，不能自动复现美国定义。</td>
</tr>
<tr class="even">
<td>F2：Barron、Kim、Lim、Stevens（1998）</td>
<td>已用相同broker构造<span class="math inline">\(\rho,h,s\)</span>及公告后减公告前变化；早期样本4,183公司年度、1,733公司、2007—2023，至少2个共同broker；有数值一致性检查。</td>
<td>broker不等于独立个体分析师；实现矩替代期望矩，EPS缩放改变h/s单位但不改变<span class="math inline">\(\rho\)</span>。排除负实际EPS，未用0.10美元阈值或缩尾。</td>
<td>测量已实施，但潜在精度未直接观测；broker依赖、EPS修订/拆股及未来实际盈余缺失约束解释。不是四大处理识别。</td>
</tr>
<tr class="odd">
<td>F3：He、Sidhu、Taylor（2019）</td>
<td>已配对同broker，前60/后30日、固定t+1，前最后/后最早、排除公告日。控制回归N=4,170，无额外固定效应；绝对surprise、对数市值、MB、预测数控制，公司/年份双向聚类，自由度16。</td>
<td>保留原始单位而非行业—年排名；broker代替分析师，原文后期选序未核实。四大/Local 8/Other代替5种代理；当前绝对消息与收益研究有符号消息不同。</td>
<td>已估计四大−Other：<span class="math inline">\(\Delta\rho=0.014621\)</span>（SE=0.007698，p=0.0757）；<span class="math inline">\(\Delta h=21.576\)</span>（p=0.6477）；<span class="math inline">\(\Delta s=94.638\)</span>（p=0.1400）。并非三项显著改善。精确排名、PSM/CEM/IMR及SOX设计未完成复现。</td>
</tr>
</tbody>
</table>
<details>
<summary>
F1：Behn, Choi and Kang (2008；与 R02 为同一论文)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>完整书目</strong>：Bruce K. Behn；Jong-Hag Choi；Tony Kang. <em>Audit Quality and Properties of Analyst Earnings Forecasts</em>. The Accounting Review83(2):327–349，2008年3月，正式版。DOI10.2308/accr.2008.83.2.327。<a href="https://scholars.cityu.edu.hk/en/publications/audit-quality-and-properties-of-analyst-earnings-forecasts/">作者机构登记</a>；<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1029757">SSRN版本记录</a>。本轮读取 本地原文核对件，7,378,930字节。搜索词：<code>"Audit Quality and Properties of Analyst Earnings Forecasts" "Behn" "Choi" "Kang"</code>。</p>
<ul>
<li>数据、单位；美国I/B/E/S预测及实际EPS、Compustat财务；审计年度1996–2001，公司年；t+1/t+2预测检验需数据至2003；最终准确度9,261、分歧3,749（p.334）</li>
<li>预测；对目标盈余公告前两个月起至公告前3日，各分析师只用最近预测，求均值；实际EPS是I/B/E/S的before extraordinary items（p.332）</li>
<li>ACCY；(ACCY=-mean(FEPS)-EPS^{actual}/P_{t-1})，P为前期末股价；越大/越接近0越准确（p.332式2）</li>
<li>DISP；(DISP=sd(FEPS)/P_{t-1})；至少4位分析师，越小分歧越少（p.333式4及fn.13）</li>
<li>删极值；ACCY&lt;−1.5删除；DISP&gt;1.5删除14例；ZMIJ、EL cap在±5；不是所有连续变量统一1%缩尾（pp.332–333）</li>
<li>审计分类；AUDITOR=Big5；ISPEC=某所某两位SIC行业客户资产平方根之和/该所全部客户资产平方根之和，用整个Compustat客户计算；少于10客户的所年ISPEC置0（p.331）</li>
<li>准确度方程；AUDITOR、ISPEC及两者交互，SIZE、SURPRISE、LOSS、ZMIJ、HORIZON、STDROE、NANA、EL、INVMR、年dummies（pp.332–334）</li>
<li>分歧方程；上述类似，但不含NANA、LOSS、EL；依旧含IMR与年dummies（p.333）</li>
<li>信息/财务控制；SIZE=市值log；SURPRISE为年度盈余变化/股价的绝对幅度控制（正文p.333），不是预测误差S；HORIZON=预测日至实际公告日平均日数的log；NANA=覆盖人数log；STDROE表注为过去5年earnings标准差；ZMIJ财务困境分数；EL实际EPS。表注/名称与更细代码未全部披露，勿凭名称重构未给细节</li>
<li>选择第一阶段；probit Big5 on SIZE、CAPINT长期资产/资产、INVREC存货及应收/资产、LEVE负债/资产、LOSS、ROA、ISSUE过去两年长期债发行超过原长期债20%；再计算IMR，所有主要模型加入（p.332 fn.10）</li>
<li>FE/SE；年dummies，公司聚类、White异方差稳健；没有报告公司FE或行业FE（p.332）</li>
<li>换所敏感性；Big5→非Big5准确度变差；非Big5→Big5准确度改善不显著、分歧下降仅边际t=1.71；这些为untabulated，不是外生换所DID（p.346及fn.25）</li>
</ul>
<p>论文p.347明确说没有显示因果关系，未知遗漏因素不能排除。probit-IMR也不是已经验证的外生IV；没有充分经济论证的第一阶段变量不能直接当我们的排除工具。</p>
<p><strong>项目差别</strong>：当前<code>abs_surprise_60</code>用绝对实际EPS作分母，不是原文股价；主S用180日中位数，原文ACCY两月均值；项目当前行情预测去重按券商，而原文按分析师；项目BKLS数据比较同券商对同一下一财年、公告前60天/后30天的预测（部分信息样本要求正实际EPS），不是原文当年公告前ACCY/DISP。<code>63_information_quality.do</code>输出delta_rho、delta_h、delta_s、修正及误差变化，是其他信息指标。可以说数据支持做邻近的预测性质检验，但不能称已复现R02，不能把分歧较小等同于审计师造成报告更准。</p>
</details>
<details>
<summary>
F2：Barron, Kim, Lim and Stevens (1998；BKLS)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>完整书目：</strong> Orie E. Barron; Oliver Kim; Steve C. Lim; Douglas E. Stevens (1998). <em>Using Analysts’ Forecasts to Measure Properties of Analysts’ Information Environment</em>. The Accounting Review 73(4), 421–433。 <a href="https://pure.psu.edu/en/publications/using-analysts-forecasts-to-measure-properties-of-analysts-inform/">机构书目</a>。核读模型、应用局限与结论（pp.423–429）；未逐式核验附录扫描证明。</p>
<p>搜索词：<code>"Using Analysts Forecasts to Measure Properties of Analysts Information Environment" Barron Kim Lim Stevens</code>。</p>
<p>这是一篇模型和测量方法文章，不是一个Big4 treatment设计。没有属于其自身的国家样本、公司年N、选择方程、匹配、结果回归controls/FE/SE、DID处理组或IV。</p>
<p>原文 pp.423–424 eq.(1)–(8)：共同先验/信号精度为h，个体私有信号误差正态、独立，私有精度可以在一般模型中不同；预测是条件期望。模型的重要条件是任意两位分析师共同的信息对全部分析师共同。所谓“私人”不等于内幕，也可来自对公开材料的不同加工。</p>
<p>原文 pp.425–428，Proposition 1/2/3与Corollary 1：</p>
<p>[ D=E[],SE=E[(实际盈利-平均预测)^2],N=. ]</p>
<p>[ V=SE+(1-1/N)D,C=SE-D/N,=C/V. ]</p>
<p>V为总体不确定性，C为共同误差的协方差部分。若进一步假定各分析师私人信息精度相同，得到：</p>
<p>[ h=C/V^2,s=D/V^2,=h/(h+s). ]</p>
<p>不能因预测分歧变小就认定信息质量改善，也不能因rho增加就认定h增加。<code>C&lt;0</code>会产生负h，不符合模型精度条件；有限样本实现误差本身不一定符合理论期望。</p>
<p>应用局限在p.429，第III节：预测偏差会污染误差和共同程度；从其他分析师行为学习的herding模糊共同/私人信息区分；理论D和SE是无条件期望，实际研究需要多个观测的聚合来减少测量误差。He的公司年plug-in值和本项目的公司年指标是实证实现，不是直接观察到真实h/s。</p>
<p><strong>项目实现差别</strong></p>
<p>本项目基于同券商而非独立个人分析师，用公司年两侧实现分歧/平方误差代入，且按He将二者除以目标年实际EPS绝对值。归一化不改变rho，但会改变h/s单位；不同研究缩放口径下的精度系数不可直接比较。原EPS的拆送股口径和修订值仍未统一，不能把条件一致性检查等同于潜在信息精度被无误差测量。</p>
</details>
<details>
<summary>
F3：He, Sidhu and Taylor (2019)｜中文逐篇说明、原文定位与检索词
</summary>
<p><strong>完整书目：</strong> Wen He; Baljit Sidhu; Stephen Taylor (2019). <em>Audit quality and properties of analysts’ information environment</em>. Journal of Business Finance &amp; Accounting 46(3–4), 400–419；在线2018。 <a href="https://doi.org/10.1111/jbfa.12358">出版记录</a> · <a href="https://opus.lib.uts.edu.au/bitstream/10453/134915/4/HST%20JBFA%202018%20August.pdf">作者接受稿</a>。方法核读2018年8月接受稿内部pp.9–21，而非正式刊页。</p>
<p>搜索词：<code>"Audit quality and properties of analysts information environment" He Sidhu Taylor</code>。</p>
<p>以下页码为<strong>接受稿内部页码</strong>，不是正式400–419页：内部p.10=PDF第12页，内部p.18=PDF第20页。原文方法见§3、selection见§4.4、SOX见§4.5；附表1/4/5在稿末。</p>
<p><strong>5.1 样本、时点、Y与审计代理</strong></p>
<ul>
<li>美国上市公司，I/B/E/S unadjusted detail年度预测+Compustat；1985–2015，最终25,111公司年、5,353公司（§3.2，内部p.10；表1）。表1从至少两位前侧预测56,621公司年，进入前后更新34,854，再按信息精度和财务资料筛选至最终样本。</li>
<li>在第t年盈利公布前60天、后30天，考察分析师对<strong>同一个t+1年</strong>盈利的更新，至少两位更新者；剔除陈旧预测并使两侧信息事件更可比。原文未在本轮明确核实多个post预测是第一份还是最后一份，故不能声称项目“最后pre/最早post”逐字来自原文。</li>
<li>构造D为个人预测EPS样本方差、SE为平均预测相对t+1实际EPS的平方误差，再分别除以|t+1实际EPS|；剔除绝对实际EPS&lt;0.10美元，剔除负h；Y为公告后−公告前的rho、h、s（§3.3 eq.4–6，内部pp.11–12）。</li>
<li>审计代理五种：BigN、全国两位SIC行业的客户销售额市场份额Share、客户数份额Sharecl、对应行业最大份额Leader/Mostcl（§3.1，内部pp.9–10；附录）。不是Behn的事务所自身客户组合比重。</li>
</ul>
<p><strong>5.2 主回归</strong></p>
<p><code>Δ信息指标 = Audit + Surp + Size + MB + Analysts</code>。Surp为t年度实现EPS与前侧均值预测差的绝对值／|t实际EPS|；Size为市值对数（附录定义），MB为市场账面比，Analysts为计算信息指标的预测人数。正文对Size有一般“市场规模”描述，编码应以附录对数定义核对。它不是项目价格图的有符号surprise，也不以预测中位数作分母。</p>
<p>由于h/s偏态，主回归使用<strong>每年每个两位SIC行业内部的变量排序</strong>，不直接拿原始h/s作OLS。作者在内部p.13脚注13将排序解释为控制行业/年度差异，主式不另列这些FE；不要改写成常规行业×年度吸收FE。SE按公司和年度双向聚类（内部p.13、表4）。</p>
<p>表4的BigN项（排序变量尺度）：Δrho=0.537，t=16.35；Δh=0.523，t=16.40；Δs=0.447，t=15.69；均标为1%显著、N=25,111。它们不是原始rho变化0.537或精度增加0.523，不能和中国原尺度系数直接比大小。其余行业代理方向一致。</p>
<p><strong>原文自述与表格的一处不一致：</strong> 正文描述三个变化均值为正，但接受稿表2中Δs均值为−14.712，中位数0.002。因此不可声称该稿的三个原始变化均值全为正。回归条件关系与原始均值是不同对象。</p>
<p><strong>5.3 selection处理与可复制细节</strong></p>
<ul>
<li>公告前后变化；审计师身份在短窗口内固定，以变化而非水平为Y；能减轻部分稳定水平混杂；不能控制企业披露能力对公告增量信息的影响</li>
<li>Heckman/IMR；第一阶段选BigN或行业专家/leader；变量规模、PPE/总资产、应收+存货/总资产、杠杆、亏损、ROA、当期债务发行；第二阶段加入IMR。只有规模在原结果控制中重叠，其余被当作主要排除变量；依赖选择方程、分布与排除限制。融资/资产结构可能影响盈利预测；原文明确承认排除变量选择影响selection结论。不是经过外生性验证的IV</li>
<li>PSM；两组选择变量：①规模+年度/行业FE；②再加PPE、应收存货、杠杆、亏损、ROA、债务发行。probit估计选择概率，按最接近倾向得分匹配；文字具体举行业专家选择；按条件可忽略选择和共同支持解释；不能控制未观测选择。精确caliper、替换方式、treatment/control比例网格及各匹配N未在存档正文披露；不能猜成1:1或0.01</li>
<li>CEM；同两组特征；变量分箱，在同箱中匹配，用Stata <code>autocuts</code>选箱；依赖选择特征和分箱。没有在正文核实具体箱边界、每格处理对照权重或匹配后N，不能补写</li>
<li>匹配后结果；重估表4；PSM对caliper/处理对照比例敏感，CEM对特征集合敏感；有的行业专家结果明显减弱，有的稳健；应报告设定敏感，不是“匹配彻底解决选择且所有结果稳健”</li>
<li>公司FE；重估eq.6加公司FE，移除年度/行业FE；作者报告方向显著；只能控制时间不变混杂，未解决时变选择。相关补充多未制表</li>
<li>重加权；没有核实主文采用IPW、overlap weighting、entropy balancing；可作为后续设计讨论，不能列为该文已完成方法</li>
</ul>
<p><strong>5.4 SOX DID</strong></p>
<p>§4.5，内部pp.19–21；表5：1998–2007美国与非美国上市公司，公司年N=13,546；非美资料Compustat Global和I/B/E/S，沿用前后预测筛选。USA为受SOX约束美国公司，PostSOX为2002之后，估计USA、Post、USA×Post并控制Surp、Size、MB、Analysts；变量按行业年度排序，USA/Post除外；SE按公司/年度双向聚类。文中另报告3年/10年窗口方向类似。</p>
<p>表5交互项：Δrho=4.875，t=2.14；Δh=4.440，t=2.21；Δs=3.652，t=2.07，均5%显著。都是该表排序尺度。eq.7正文还列Audit控制，但表5模型标题和表内没有Audit，报告应保留“正文与表格列式不同”，不能断言表5确实估计了Audit项。</p>
<p>本轮未核实动态leads/lags、事前趋势检验、错位处理、国家特定趋势或对照市场名单。因此这是美国/非美的政策前后DID，不是现代交错处理事件研究。要解释成SOX作用，需要可比趋势、无其他美国差异冲击、对照不受SOX直接或间接影响等条件；SOX同时改变披露、监管等，政策效应不能直接转换为聘用四大效果。本项目没有同一美国/非美监管处理对照体系，不能直接复制此识别。</p>
<p>其他敏感性：§4.3的放宽前侧预测、异质私人精度方法、行业划分、audit×surprise，以及费用/任期/报告滞后，大多未制表；未核实精确N、SE和所有模型设置。没有在本记录另引入新机制文章。</p>
</details>
<details>
<summary>
补充：两篇早期中国 ERC 文献（仅核实摘要，未补造方法细节）
</summary>
<p><strong>Ferdinand A. Gul; Sunny Y. J. Sun; Judy S. L. Tsui (2003).</strong> <em>TRACKS: Audit Quality, Earnings, and the Shanghai Stock Market Reaction</em>. Journal of Accounting, Auditing &amp; Finance 18(3), 411–427。<a href="https://doi.org/10.1177/0148558X0301800306">出版记录</a>。摘要报告上海1996—1997年659观测及审计质量、盈余与市场反应的联系。完整样本单位、控制、FE、SE与窗口未核实，故不进入上面的已核读方法对照。</p>
<p>搜索词：<code>"TRACKS Audit Quality Earnings Shanghai Stock Market Reaction" Gul Sun Tsui</code>。</p>
<p><strong>Z. Jun Lin; Ming Liu; Zhemin Wang (2009).</strong> <em>Market Implications of Audit Quality and Auditor Switches: Evidence from China</em>. Journal of International Financial Management &amp; Accounting 20(1), 35–78。<a href="https://doi.org/10.1111/j.1467-646X.2009.01026.x">出版记录</a>。摘要涉及 Top 10 换所及正负异常盈余下的 ERC；未核实原文完整N、控制、FE、SE，不把二手报道的2002—2004年区间作为已核验主样本。</p>
<p>搜索词：<code>"Market Implications of Audit Quality and Auditor Switches" Lin Liu Wang</code>。</p>
</details>
<p><strong>与后文的对应。</strong> 第2节区分当年客户匹配、进入前特征和相邻年度流动；第3节在共同样本上调整可观察特征；第4节考察同一客户的换所及事前匹配，保留动态和批次支持；第5节区分连续盈利消息的斜率、固定消息水平差、门槛和非线性曲线。现有公共数据不恢复中国私有审计前报表，也没有已验证的四大聘用工具变量。客户匹配不能自动解决同期客户变化，市场斜率不能自动分离真实消息质量和认证渠道。这些是解释现有证据时的界限，而非新增模型或检验的宣告。</p>
</section>
</section>
<section class="level2" id="客户选择与审计意见四大如何形成较低风险的客户组合">
<h2 class="anchored" data-anchor-id="客户选择与审计意见四大如何形成较低风险的客户组合">2. 客户事前差异与可观察选择</h2>
<section class="level3" id="进入前客户特征">
<h3 class="anchored" data-anchor-id="进入前客户特征">2.1 进入前客户特征</h3>
<p>首次合格换入要求此前连续三年非四大、从进入年起连续三年四大。204家公司的进入年份为1999—2022，193家此前没有四大观测，11家已有四大经历；因此“首次合格换入”不等于全部为首次聘用四大。对照为全观察期始终非四大的公司，按进入者批次组成比较相同日历年。事后三年留任要求也界定了这项比较的适用对象。</p>
<p>严格口径违规率在进入前第三年为1.96%，对照4.79%；进入前一年仍为1.96%，对照5.45%。亏损率和规模也显示事前差异。相反，进入者严格重述率由1.47%升至3.43%；公司内配对变化为+1.96个百分点，SE=1.20，95%CI=[−0.40,4.32]，p=0.103。中间口径变化+4.90（SE=2.67，CI=[−0.36,10.17]，p=0.068），宽口径+10.78（SE=3.39，CI=[4.10,17.47]，p=0.002）。这些是未经日历冲击调整的描述变化，不支持统一的“质量改善后进入”过程。</p>
<figure class="latex-table figure">
<img alt="Characteristics Before First Qualifying Big 4 Entry" class="figure-img" loading="lazy" src="tables/big4_evidence/pre_entry_characteristics.png" style="width:734px"/>
<figcaption>Characteristics Before First Qualifying Big 4 Entry</figcaption>
</figure>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_evidence/pre_entry_trajectory_strict.png" style="width:100.0%"/></p>
<figcaption>进入四大前的客户特征与严格失败率</figcaption>
</figure>
</div>
</section>
<section class="level3" id="年度客户匹配可观察调整后仍有质量差异">
<h3 class="anchored" data-anchor-id="年度客户匹配可观察调整后仍有质量差异">2.2 年度客户匹配：可观察调整后仍有质量差异</h3>
<p>客户特征调整的比较思路对应 Lawrence 等（2011）、DeFond 等（2017）和 Eshleman 与 Guo（2014）；具体匹配方向、放回、卡尺与推断差别见第1节，本项目保留既定设定。</p>
<p>年度 PSM 比较当年四大与匹配非四大客户。两套候选样本均为70,677公司年度，包含4,782个四大观测；不同匹配对照分别为3,359（五项）和3,320（九项）。本隔离诊断按授权排除905个单边行业／年份观测及000506–2006、000892–2008两条非四大观测；未把这一排除推广到正式DTA或换所PSM-DID。</p>
<p>五项选择模型包含规模、杠杆、亏损、ROA、Z-score及缺失标记；九项另含杠杆变动、报告时滞、CFO和上市年限。行业、年份进入Logit，但不是精确匹配限制；使用有放回的1:1最近邻、无卡尺。五项未预警综合失败、重述和违规差异分别为−1.568、−0.669、−1.066个百分点；九项为−1.882、−1.192、−0.795，六项均在其AI稳健推断下达到1%显著水平。</p>
<p>这些结果支持可观察特征调整后的客户质量差异。AI稳健标准误没有按公司聚类；年度观测的公司内相关性仍需与其他公司聚类设计联合理解。五项并未增加四大处理数量，对照权重ESS为270.47，低于九项的371.30；九项仍有ROA/CFO尾部和方差不平衡。因此，匹配成功及显著性不意味着客户选择已消除，也不据此判定五项优于九项。</p>
<figure class="latex-table figure">
<img alt="Annual Client Matching: Five and Nine Selection Controls" class="figure-img" loading="lazy" src="tables/big4_evidence/annual_client_psm.png" style="width:734px"/>
<figcaption>Annual Client Matching: Five and Nine Selection Controls</figcaption>
</figure>
</section>
<section class="level3" id="客户进入留任与退出">
<h3 class="anchored" data-anchor-id="客户进入留任与退出">2.3 客户进入、留任与退出</h3>
<p>Johnstone 与 Bedard（2004）直接观察事务所的客户接受和终止决定；本节仅观察公共数据中的进入与退出，二者不能互相替代。</p>
<p>相邻年度风险集中，非四大进入为342/61,459（0.56%），四大退出为283/4,396（6.44%）。MAO四大客户44/103次年退出（42.72%），非MAO客户239/4,293（5.57%）；44个事件涉及40家公司，其中一个后任事务所名称与ID缺失。没有次年观测不能记为退出。</p>
<p>沿用九项控制、缺失标记、公司和行业×年份固定效应、公司聚类，MAO对应四大客户次年退出概率高30.40个百分点（SE=7.35，CI=[15.96,44.84]，p&lt;0.001）；非四大进入概率低0.249个百分点（SE=0.121，CI=[−0.485,−0.012]，p=0.039）。GC对应退出高20.62个百分点（p=0.042），进入差异不显著。这里识别的是意见与流动的条件关联，尚不能分辨审计师辞任和客户改聘。</p>
<figure class="latex-table figure">
<img alt="Audit Opinions and Next-Year Big 4 Client Transitions" class="figure-img" loading="lazy" src="tables/big4_evidence/client_flows.png" style="width:734px"/>
<figcaption>Audit Opinions and Next-Year Big 4 Client Transitions</figcaption>
</figure>
<details>
<summary>
补充：客户变更公告与意见预测的完整证据
</summary>
<p>变更公告中的微观线索</p>
<p>对收到 MAO 后更换事务所的案例分析进一步佐证了双方的动态博弈：</p>
<ul>
<li><strong>深圳华强（2001→2002）：</strong> 数据库记录为辞任，公告称服务未达要求，改聘本土所；</li>
<li><strong>退市拉夏（2019→2020）：</strong> 公告提及“合理控制审计成本”，另一来源为收费分歧；尚无明确风险分歧证据；</li>
<li><strong>卓郎智能（2019→2020）：</strong> 集团控股股东主导更换；</li>
<li><strong>上海临港（2014→2015）：</strong> 重大资产重组导致审计机构重新洗牌；</li>
<li><strong>新城控股（2023→2024）：</strong> 业务发展与整体审计需求调整；</li>
<li><strong>鼎信通讯（2023→2024）：</strong> 连续服务超过十年，基于独立性与招投标程序轮换。</li>
</ul>
<p>这些案例提供任期、费用、集团安排及重组等具体线索。深圳华强的“辞任”原因码与董事会改聘文字不一致；新城控股公告还明确不存在工作、费用或意见分歧，不能将这些记录统一归为四大主动辞任。</p>
<p>以下综合机制表沿用其独立回归样本；Panel A为原流动规格，最新严格相邻年度的流动结果以正文表为准，两者不混作同一估计。Panels B—E保留意见预测、分类概率和客户特征证据。</p>
<p>综合机制表：流动、预警与风险构成</p>
<p>Table M1 将客户进入、退出、预警后风险差异及财务特征整合汇报：</p>
<figure class="latex-table figure">
<img alt="Table M1, Panel A" class="figure-img" loading="lazy" src="tables/big4_mechanism/client_selection_opinion_mechanism_full_p01.png"/>
<figcaption>Table M1, Panel A</figcaption>
</figure>
<figure class="latex-table figure">
<img alt="Table M1, Panel B" class="figure-img" loading="lazy" src="tables/big4_mechanism/client_selection_opinion_mechanism_full_p02.png"/>
<figcaption>Table M1, Panel B</figcaption>
</figure>
<figure class="latex-table figure">
<img alt="Table M1, Panel C" class="figure-img" loading="lazy" src="tables/big4_mechanism/client_selection_opinion_mechanism_full_p03.png"/>
<figcaption>Table M1, Panel C</figcaption>
</figure>
<figure class="latex-table figure">
<img alt="Table M1, Panel D" class="figure-img" loading="lazy" src="tables/big4_mechanism/client_selection_opinion_mechanism_full_p04.png"/>
<figcaption>Table M1, Panel D</figcaption>
</figure>
<figure class="latex-table figure">
<img alt="Table M1, Panel E" class="figure-img" loading="lazy" src="tables/big4_mechanism/client_selection_opinion_mechanism_full_p05.png"/>
<figcaption>Table M1, Panel E</figcaption>
</figure>
<p><span id="full-12_big4_effect-3"></span> <span id="certification-story"></span> <span id="certification-market"></span> <span id="certification-tests"></span></p>
</details>
</section>
</section>
<section class="level2" id="audit-outcome-levels">
<h2 class="anchored" data-anchor-id="audit-outcome-levels">3. 审计结果水平差异</h2>
<section class="level3" id="三种定义与三种分母">
<h3 class="anchored" data-anchor-id="三种定义与三种分母">3.1 三种定义与三种分母</h3>
<p>三种重述定义按既有规则保留：严格、中间（财务变更且非明确无盈余影响）和宽口径，三者为包含关系，不是互斥类型。失败按被更正或违规涉及的财年归属；意见为当年审计报告的MAO。</p>
<p><span class="math display">\[
P(Y=1),\qquad P(Y=1,\ MAO=0),\qquad P(Y=1\mid MAO=0).
\]</span></p>
<p>回归中的未预警失败是第二项的联合指示变量，样本不按MAO=0筛掉。第三项才是在非MAO客户中的条件概率。严格综合失败的无条件率，四大、本土八大、Other分别为2.26%、6.47%、7.84%；联合率分别为1.99%、5.37%、5.94%。原始资料重建与正式面板逐键一致，但事件0只表示下载来源没有合格匹配记录，不能证明未发生事件。</p>
<p>旧重述公告库覆盖2001—2021、新库覆盖2017—2026；旧库盈余方向大量缺失，影响严格定义的早期覆盖。重述公告与被更正财年的中位间隔约1—2年，违规公告间隔中位3年。2021是旧库公告末年，不是事件发生年的无缝拼接点；末期较低率也可能包含以后才发现的问题。</p>
<figure class="latex-table figure">
<img alt="Audit Failures by Auditor Group and Denominator" class="figure-img" loading="lazy" src="tables/big4_evidence/audit_failure_probabilities.png" style="width:734px"/>
<figcaption>Audit Failures by Auditor Group and Denominator</figcaption>
</figure>
</section>
<section class="level3" id="共同样本下的嵌套比较">
<h3 class="anchored" data-anchor-id="共同样本下的嵌套比较">3.2 共同样本下的嵌套比较</h3>
<p>这一比较与 Chen 等（2022）区分客户输入质量和审计输出的思路相关；我们只能调整公共财务特征，未观察其私有审计前报表。</p>
<p>在同一71,241公司年度、5,626公司簇中，严格未预警综合失败的四大系数从无调整−3.66个百分点，变为公司及行业×年份FE下−1.18（SE=0.68，p=0.082），再加九项controls后−1.64（SE=0.69，p=0.017）。重述完整规格−0.42（SE=0.46，p=0.367），违规−1.51（SE=0.57，p=0.008）。总体质量梯度主要由违规及综合失败支持，不能把严格重述的不显著省略，也不能把列间系数变化解释成selection比例。</p>
<p>九项控制为规模、杠杆、亏损、ROA、Z-score、杠杆变动、年报披露时滞、CFO、上市年限及各自缺失标记；沿用年份中位数插补、全样本中位数回退。固定效应和controls调整的是本模型可观测差异，不自动解决时间变化的客户选择。</p>
<figure class="latex-table figure">
<img alt="Big 4 Client Differences on a Common Sample" class="figure-img" loading="lazy" src="tables/big4_evidence/failure_level_nested.png" style="width:734px"/>
<figcaption>Big 4 Client Differences on a Common Sample</figcaption>
</figure>
<details>
<summary>
补充：原图、长期趋势与客户—事务所排序
</summary>
<section class="level4" id="中国审计市场的分层与长期趋势">
<h4 class="anchored" data-anchor-id="中国审计市场的分层与长期趋势">中国审计市场的分层与长期趋势</h4>
<p>将事务所分为四大（Big 4）、本土八大（Local 8）和其他事务所（Others）。按审计费用衡量的市场份额展现了市场结构的演化轨迹；而质量比较则以公司—年为基本观测单元。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/audit_quality/market_share_by_audit_fee.png" style="width:100.0%"/></p>
<figcaption>按审计费用计算的事务所市场份额</figcaption>
</figure>
</div>
<p>四大客户在资产规模、审计费用及风险结构上明显不同。由此，四大与其他事务所的结果差异可能同时来自客户选择、审计服务以及事件被监管发现的过程。</p>
<section class="level5" id="市场质量的宏观趋势">
<h5 class="anchored" data-anchor-id="市场质量的宏观趋势">1.1 市场质量的宏观趋势</h5>
<p>为考察全市场审计质量的长期演进，模型采用三基线检验：</p>
<p><span class="math display">\[
Y^m_{it} = \alpha_i + \sum_{\tau \ne 2000} \eta^m_{\tau, s} \mathbf{1}\{\text{Year}=t\} + \mathbf{X}_{it}'\gamma_m + \varepsilon^m_{it}.
\]</span></p>
<p>以 2000 年为基期，吸收公司固定效应并按公司聚类。三条基线分别对应：(1) 全部非平衡活跃公司；(2) 长期存续基线（2000—2024 年观测不少于 22 年）；(3) 本地五年连续基线（<span class="math inline">\([t-2, t+2]\)</span> 窗口连续观测）。</p>
<p><strong>审计失败趋势</strong></p>
<p>综合失败率在各基线下均呈现 2008 年后上升、2016—2018 年达到阶段高点后逐步回落的非单调模式；长期存续样本的上升幅度更为明显。</p>
<p><img alt="2000—2024 年综合审计失败率的三基线宏观趋势。" class="img-fluid" data-fig-cap="综合审计失败率的宏观趋势。点估计与 95% 置信区间均相对 2000 年；三条线的差异反映样本存续与连续观测要求。" src="figures/audit_quality/trend_any_failure_clean.png" style="width:100.0%"/></p>
<p>财务重述与财务违规趋势提供了失败率的结构性拆解：单个指标的变化既反映审计质量，也受到监管披露政策与执法力度的影响。</p>
<p><img alt="2000—2024 年财务重述率的三基线宏观趋势。" class="img-fluid" data-fig-cap="财务重述率的宏观趋势：相对 2000 年的公司固定效应条件均值。" src="figures/audit_quality/trend_restated_clean.png" style="width:100.0%"/></p>
<p><img alt="2000—2024 年财务违规率的三基线宏观趋势。" class="img-fluid" data-fig-cap="财务违规率的宏观趋势：相对 2000 年的公司固定效应条件均值。" src="figures/audit_quality/trend_violated_clean.png" style="width:100.0%"/></p>
<p><strong>盈余管理与指标覆盖率</strong></p>
<p>Jones 异常应计绝对值也展现出类似的宏观演变特征：</p>
<p><img alt="2000—2024 年 Jones 异常应计绝对值的三基线宏观趋势。" class="img-fluid" data-fig-cap="Jones 异常应计绝对值的宏观趋势。" src="figures/audit_quality/trend_abs_da_jones.png" style="width:100.0%"/></p>
<p>主要审计质量指标在 2000—2024 年间的覆盖率如下：违规、重述与审计意见指标保持全覆盖；审计费用在 2012 年后基本全覆盖；而应计盈余管理等财务指标覆盖率受披露完备性约束呈现一定波动。</p>
<p><img alt="主要审计质量指标在 2000—2024 年的年度覆盖率。" class="img-fluid" data-fig-cap="主要指标的年度覆盖率（占当年 A 股上市公司总数比例）。" src="figures/audit_quality/00_all_metrics_coverage_rate_trend.png" style="width:100.0%"/></p>
</section>
<section class="level5" id="事务所类型横截面特征">
<h5 class="anchored" data-anchor-id="事务所类型横截面特征">1.2 事务所类型横截面特征</h5>
<p>下表汇报不同事务所层级的客户群特征比较。四大客户的非标意见率仅为 2.24%，显著低于本土八大（4.51%）与其他事务所（9.44%）；审计收费均值约为本土八大的 3.7 倍，客户市值均值约为 6.9 倍。</p>
<figure class="latex-table figure" id="latex-table-2">
<img alt="Table 2: Other Outcomes by Audit-Firm Group" class="figure-img" loading="lazy" src="tables/big4_effect_latex/02_other_outcomes_descriptive_full.png"/>
<figcaption>Table 2: Other Outcomes by Audit-Firm Group</figcaption>
</figure>
<p><span id="full-12_big4_effect-2"></span></p>
</section>
<section class="level5" id="重述披露时滞与原分层图">
<h5 class="anchored" data-anchor-id="重述披露时滞与原分层图">重述披露时滞与原分层图</h5>
<p>原图沿用各自构建口径；当前严格定义及分母的精确比较以上表为准。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img alt="实质性财务重述按公告年与被重述会计年度之差统计的数量分布" class="img-fluid figure-img" src="figures/big4_effect_notebook/restatement_lag_new.png" style="width:100.0%"/></p>
<figcaption>实质性财务重述的公告时滞分布</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/audit_quality_baseline/restatement_static_3panels.png" style="width:100.0%"/></p>
<figcaption>总体重述及分类重述概率：标准无保留意见样本</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/audit_quality_baseline/violation_overall_static.png" style="width:100.0%"/></p>
<figcaption>总体违规概率：标准无保留意见样本</figcaption>
</figure>
</div>
</section>
<section class="level5" id="客户与事务所akm排序">
<h5 class="anchored" data-anchor-id="客户与事务所akm排序">客户与事务所AKM排序</h5>
<p>客户与事务所的 AKM 排序</p>
<p>为了在控制公司个体固定效应的同时分离事务所质量，我们估计公司、事务所和年份三向固定效应的 AKM 模型：</p>
<p><span class="math display">\[
Y_{ift} = \mathbf{X}_{it}'\gamma + \alpha_i + \psi_f + \lambda_t + \varepsilon_{ift}.
\]</span></p>
<p>其中 <span class="math inline">\(\psi_f\)</span> 为事务所固定效应，<span class="math inline">\(\alpha_i\)</span> 为公司固定效应。</p>
<p><img alt="按四大、本土八大和其他事务所分组的有效客户数分布。" class="img-fluid" data-fig-cap="AKM 事务所固定效应的可识别样本分布。" src="figures/audit_firm_akm/audit_firm_valid_client_distribution.png" style="width:100.0%"/></p>
<p><span id="sec-tier-other-reference"></span></p>
<section class="level6" id="sec-audit-firm-fe-distributions">
<h6 class="anchored" data-anchor-id="sec-audit-firm-fe-distributions">事务所 FE 的分布</h6>
<p>以下四张原图分别展示综合未预警失败、重述、违规和 Jones 异常应计绝对值的 audit-firm FE 分布。黑色虚线为 Other 组均值，彩色实线为各组均值；保留原图的固定效应尺度。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/audit_firm_akm/audit_firm_fe_distribution_any_failure_clean.png" style="width:100.0%"/></p>
<figcaption>Audit-firm FE distribution: Any unwarned failure</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/audit_firm_akm/audit_firm_fe_distribution_restated_clean.png" style="width:100.0%"/></p>
<figcaption>Audit-firm FE distribution: Unwarned restatement</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/audit_firm_akm/audit_firm_fe_distribution_violated_clean.png" style="width:100.0%"/></p>
<figcaption>Audit-firm FE distribution: Unwarned violation</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/audit_firm_akm/audit_firm_fe_distribution_abs_da_jones.png" style="width:100.0%"/></p>
<figcaption>Audit-firm FE distribution: Absolute Jones DA</figcaption>
</figure>
</div>
</section>
<section class="level6" id="sec-audit-firm-scatter">
<h6 class="anchored" data-anchor-id="sec-audit-firm-scatter">客户 FE 与事务所 FE 的联合散点图</h6>
<p>每个点代表一家事务所：横轴是 audit-firm FE，纵轴是该事务所客户的平均 client FE，每名客户等权。虚线标示 Other 组在两个维度上的均值，点的大小反映有效客户数。这组图展示客户与事务所的匹配分布，不能直接解释为换所的因果效应。</p>
<div class="quarto-float quarto-figure quarto-figure-center anchored" id="fig-audit-firm-scatter-all">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-audit-firm-scatter-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img class="img-fluid figure-img" src="figures/audit_firm_akm/tier_audit_firm_scatter_any_failure_clean_all.png" style="width:100.0%"/>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-audit-firm-scatter-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">图 1: Audit-firm FE and mean client FE: Any unwarned failure, all FEs</figcaption>
</figure>
</div>
<div class="quarto-float quarto-figure quarto-figure-center anchored" id="fig-audit-firm-scatter-significant">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-audit-firm-scatter-significant-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img class="img-fluid figure-img" src="figures/audit_firm_akm/tier_audit_firm_scatter_any_failure_clean_significant.png" style="width:100.0%"/>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-audit-firm-scatter-significant-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">图 2: Audit-firm FE and mean client FE: Any unwarned failure, significant FEs</figcaption>
</figure>
</div>
<p>注：第二张按原程序保留事务所 FE 与客户 FE 均满足 p&lt;0.10 的记录，再聚合到事务所层面；该图是显著性筛选后的展示，与全样本图的覆盖不同。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/audit_firm_akm/tier_audit_firm_scatter_abs_da_jones_all.png" style="width:100.0%"/></p>
<figcaption>Audit-firm FE and mean client FE: Absolute Jones DA, all FEs</figcaption>
</figure>
</div>
<p><strong>补充的类别回归。</strong> 以 Other 为基准、控制客户和年份 FE 后，四大与本土八大的未预警综合失败系数分别为 −0.0345（p=0.001）和 −0.0153（p=0.020）；四大相对本土八大的差异为 −0.0192（p=0.048）。四大相对 Other 的违规系数为 −0.0270（p=0.002），重述为 −0.0129（p=0.058），Jones 异常应计绝对值为 −0.0083（p=0.022）。这是事务所类别回归的条件差异，不是对上述逐家事务所 FE 取均值后作差。</p>
<p><strong>截面事实的推论与疑问：</strong> 上述截面比较与 AKM 排序确立了四大客户更少发生审计失败的经验事实。但这究竟源于四大对企业财报生产的“直接治理改善（Treatment Effect）”，还是源于“优质客户与顶级事务所的主动匹配（Selection / Sorting）”？回答这一问题的关键在于检验企业在更换事务所前后的动态变化。</p>
<p><span id="full-12_big4_effect-5"></span></p>
</section></section></section></details>
</section>
</section>
<section class="level2" id="识别检验换入和换出四大后是否改善">
<h2 class="anchored" data-anchor-id="识别检验换入和换出四大后是否改善">4. 换所及PSM-DID：同一客户的变化</h2>
<section class="level3" id="三口径换入与换出">
<h3 class="anchored" data-anchor-id="三口径换入与换出">4.1 三口径换入与换出</h3>
<p>换入以始终非四大客户为对照，换出以始终四大客户为对照，保留既有稳定事件要求、九项controls、公司及行业×年份FE和公司聚类。当前自然样本换入严格综合失败−2.37个百分点（SE=1.09，p=0.030），严格重述−1.09（SE=0.77，p=0.158），违规−1.58（SE=0.85，p=0.062）。中间综合失败与重述分别−8.58和−8.08，宽口径分别−9.52和−8.96；换出未出现同样清楚的对称上升。</p>
<p>这比“换入没有用”的概括更具体：改进证据受测量定义和样本设计影响，需要结合动态路径、匹配比较和前期支持判断。</p>
<figure class="latex-table figure">
<img alt="Switching DID Across Restatement Definitions" class="figure-img" loading="lazy" src="tables/big4_evidence/switching_failure_definitions.png" style="width:734px"/>
<figcaption>Switching DID Across Restatement Definitions</figcaption>
</figure>
</section>
<section class="level3" id="九项基线匹配did及支持诊断">
<h3 class="anchored" data-anchor-id="九项基线匹配did及支持诊断">4.2 九项基线匹配DID及支持诊断</h3>
<p>事前匹配与前后比较可与 Jiang 等（2019）的设计对照；该文的事务所收购处理与本项目普通换入不同，本节没有采用其收购工具变量。</p>
<p>匹配在换入前一年进行，窗口为[−3,+2]，使用九项事前控制和缺失标记、行业与年份，不加入失败历史。回归吸收stack×公司、stack×行业×年份FE，保留九项结果controls，按原公司聚类。最终匹配加权回归包含1,194个堆叠行、113家处理和102家对照；公司可在多个批次出现，不能把堆叠N当作唯一公司年度。</p>
<p>中间口径综合失败−11.85个百分点（SE=3.78，CI=[−19.30,−4.40]，p=0.002）、重述−9.11（SE=3.11，CI=[−15.24,−2.97]，p=0.004）。17次逐一剔除cohort时，两者系数均为负、95%区间均不含零。严格综合失败−5.28（SE=2.56，CI=[−10.32,−0.25]，p=0.040），但剔除2017后变为−1.44、CI=[−4.26,1.39]。严格重述、违规和宽口径的非显著区间在下表保留，不能据此证明效应为零。</p>
<p>样本减少本身不否定匹配DID；需要核对最终比较和协变量。最终回归权重下ROA均值4.60%对3.28%，报告时滞93.64天对97.57天，SMD分别0.247、−0.211，仍有分布差异。36家原配对照退出的处理公司中32家所在cohort仍有对照，但部分cohort确实缺少直接前后比较；61个非零FE净化处理事件只是支持描述，没有数量有效性门槛。当前五项年度PSM不替代这套九项换所结果；五项是否同时用于34的选择与结果方程尚待确认。</p>
<figure class="latex-table figure">
<img alt="Switch-in DID Before and After Baseline Matching" class="figure-img" loading="lazy" src="tables/big4_evidence/matched_switching_did.png" style="width:734px"/>
<figcaption>Switch-in DID Before and After Baseline Matching</figcaption>
</figure>
</section>
<section class="level3" id="动态路径与修正的sa">
<h3 class="anchored" data-anchor-id="动态路径与修正的sa">4.3 动态路径与修正的SA</h3>
<p>SA已将controls移至协变量位置，换入样本62,665行、5,191公司簇，换出2,530行、294簇，120个动态项均有有限正SE。换入第+5年严格综合失败−5.11个百分点（SE=2.26，CI=[−9.54,−0.69]，p=0.024）、严格重述−3.90（SE=1.77，CI=[−7.36,−0.44]，p=0.027）；第0至+4年5%区间均跨零，违规处理后项也均跨零。换出前已有部分显著差异。后期单项显著不等于全部动态改善，也不从单项前期不显著推出联合平行趋势。</p>
<details>
<summary>
补充：各动态估计器的完整原设定结果
</summary>
<p>动态路径与多种前沿估计器检验</p>
<p>以换所前一年（<span class="math inline">\(k=-1\)</span>）为基期，我们并列检验 TWFE、Sun &amp; Abraham (2021)、Callaway &amp; Sant’Anna (2021)、de Chaisemartin &amp; D’Haultfœuille (2020) 以及 Stacked DID 估计结果。</p>
<p><strong>TWFE 动态估计</strong></p>
<p>换入后各期的综合失败与违规置信区间均跨越零线；且换入前两年的重述系数已经显著为负（<span class="math inline">\(-2.3\)</span> 个百分点），存在显著的事前趋势（pre-trends）。换出四大后亦未出现对称的失败率上升。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_twfe_any_failure_clean_up.png" style="width:100.0%"/></p>
<figcaption>TWFE：未预警的重述或违规，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_twfe_restated_clean_up.png" style="width:100.0%"/></p>
<figcaption>TWFE：未预警的重述，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_twfe_violated_clean_up.png" style="width:100.0%"/></p>
<figcaption>TWFE：未预警的违规，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_twfe_any_failure_clean_down.png" style="width:100.0%"/></p>
<figcaption>TWFE：未预警的重述或违规，换出四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_twfe_restated_clean_down.png" style="width:100.0%"/></p>
<figcaption>TWFE：未预警的重述，换出四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_twfe_violated_clean_down.png" style="width:100.0%"/></p>
<figcaption>TWFE：未预警的违规，换出四大</figcaption>
</figure>
</div>
<figure class="latex-table figure" id="latex-table-19">
<img alt="Table 19: TWFE Event Study of Big 4 Switching" class="figure-img" loading="lazy" src="tables/big4_effect_latex/18_eventstudy_twfe_full.png"/>
<figcaption>Table 19: TWFE Event Study of Big 4 Switching</figcaption>
</figure>
<p><strong>Sun &amp; Abraham (2021) 异质性稳健估计</strong></p>
<p>以下保留原 SA 设定输出供核对；原 controls 位置已修正，正文解释以修正后的完整路径为准。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_sa_any_failure_clean_up.png" style="width:100.0%"/></p>
<figcaption>Sun–Abraham：未预警的重述或违规，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_sa_restated_clean_up.png" style="width:100.0%"/></p>
<figcaption>Sun–Abraham：未预警的重述，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_sa_violated_clean_up.png" style="width:100.0%"/></p>
<figcaption>Sun–Abraham：未预警的违规，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_sa_any_failure_clean_down.png" style="width:100.0%"/></p>
<figcaption>Sun–Abraham：未预警的重述或违规，换出四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_sa_restated_clean_down.png" style="width:100.0%"/></p>
<figcaption>Sun–Abraham：未预警的重述，换出四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_sa_violated_clean_down.png" style="width:100.0%"/></p>
<figcaption>Sun–Abraham：未预警的违规，换出四大</figcaption>
</figure>
</div>
<figure class="latex-table figure" id="latex-table-20">
<img alt="Table 20: Sun–Abraham Event Study of Big 4 Switching" class="figure-img" loading="lazy" src="tables/big4_effect_latex/19_eventstudy_sun_abraham_full.png"/>
<figcaption>Table 20: Sun–Abraham Event Study of Big 4 Switching</figcaption>
</figure>
<p><strong>Callaway &amp; Sant’Anna (2021) CS-DID 估计</strong></p>
<p>换入四大的平均综合失败效应为 <span class="math inline">\(-1.46\)</span> 个百分点（95% 区间 <span class="math inline">\([-4.82, 1.90]\)</span>，包含零线）；平均违规效应为 <span class="math inline">\(+0.23\)</span> 个百分点。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_csdid_any_failure_clean_up.png" style="width:100.0%"/></p>
<figcaption>Callaway–Sant’Anna：未预警的重述或违规，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_csdid_restated_clean_up.png" style="width:100.0%"/></p>
<figcaption>Callaway–Sant’Anna：未预警的重述，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_csdid_violated_clean_up.png" style="width:100.0%"/></p>
<figcaption>Callaway–Sant’Anna：未预警的违规，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_csdid_any_failure_clean_down.png" style="width:100.0%"/></p>
<figcaption>Callaway–Sant’Anna：未预警的重述或违规，换出四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_csdid_restated_clean_down.png" style="width:100.0%"/></p>
<figcaption>Callaway–Sant’Anna：未预警的重述，换出四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_csdid_violated_clean_down.png" style="width:100.0%"/></p>
<figcaption>Callaway–Sant’Anna：未预警的违规，换出四大</figcaption>
</figure>
</div>
<figure class="latex-table figure" id="latex-table-24">
<img alt="Table 24: Callaway–Sant’Anna Event-Study Summary" class="figure-img" loading="lazy" src="tables/big4_effect_latex/23_eventstudy_csdid_summary_full.png"/>
<figcaption>Table 24: Callaway–Sant’Anna Event-Study Summary</figcaption>
</figure>
<p><strong>de Chaisemartin &amp; D’Haultfœuille (2020) 估计</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_dcdh_any_failure_clean_up.png" style="width:100.0%"/></p>
<figcaption>de Chaisemartin–D’Haultfœuille：未预警的重述或违规，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_dcdh_restated_clean_up.png" style="width:100.0%"/></p>
<figcaption>de Chaisemartin–D’Haultfœuille：未预警的重述，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_dcdh_violated_clean_up.png" style="width:100.0%"/></p>
<figcaption>de Chaisemartin–D’Haultfœuille：未预警的违规，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_dcdh_any_failure_clean_down.png" style="width:100.0%"/></p>
<figcaption>de Chaisemartin–D’Haultfœuille：未预警的重述或违规，换出四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_dcdh_restated_clean_down.png" style="width:100.0%"/></p>
<figcaption>de Chaisemartin–D’Haultfœuille：未预警的重述，换出四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_dcdh_violated_clean_down.png" style="width:100.0%"/></p>
<figcaption>de Chaisemartin–D’Haultfœuille：未预警的违规，换出四大</figcaption>
</figure>
</div>
<figure class="latex-table figure" id="latex-table-21">
<img alt="Table 21: de Chaisemartin–D’Haultfoeuille Event Study of Big 4 Switching" class="figure-img" loading="lazy" src="tables/big4_effect_latex/20_eventstudy_dcdh_full.png"/>
<figcaption>Table 21: de Chaisemartin–D’Haultfoeuille Event Study of Big 4 Switching</figcaption>
</figure>
<p><strong>堆叠事件研究（Stacked DID）与稳健性检验</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_stacked_any_failure_clean_up.png" style="width:100.0%"/></p>
<figcaption>堆叠事件研究：未预警的重述或违规，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_stacked_restated_clean_up.png" style="width:100.0%"/></p>
<figcaption>堆叠事件研究：未预警的重述，换入四大</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_eventstudy_stacked_violated_clean_up.png" style="width:100.0%"/></p>
<figcaption>堆叠事件研究：未预警的违规，换入四大</figcaption>
</figure>
</div>
<figure class="latex-table figure" id="latex-table-22">
<img alt="Table 22: Stacked Event Study of Switching into Big 4" class="figure-img" loading="lazy" src="tables/big4_effect_latex/21_eventstudy_stacked_full.png"/>
<figcaption>Table 22: Stacked Event Study of Switching into Big 4</figcaption>
</figure>
<p>在按市值加权或排除低市值对照公司后，估计结果依然未见显著下降：</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_robustness_any_failure_clean_drop_small_controls.png" style="width:100.0%"/></p>
<figcaption>换入四大稳健性：未预警的重述或违规，排除低市值对照公司</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_robustness_any_failure_clean_value_weighted.png" style="width:100.0%"/></p>
<figcaption>换入四大稳健性：未预警的重述或违规，市值加权</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_robustness_restated_clean_drop_small_controls.png" style="width:100.0%"/></p>
<figcaption>换入四大稳健性：未预警的重述，排除低市值对照公司</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_robustness_restated_clean_value_weighted.png" style="width:100.0%"/></p>
<figcaption>换入四大稳健性：未预警的重述，市值加权</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_robustness_violated_clean_drop_small_controls.png" style="width:100.0%"/></p>
<figcaption>换入四大稳健性：未预警的违规，排除低市值对照公司</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect/failure_robustness_violated_clean_value_weighted.png" style="width:100.0%"/></p>
<figcaption>换入四大稳健性：未预警的违规，市值加权</figcaption>
</figure>
</div>
<figure class="latex-table figure" id="latex-table-23">
<img alt="Table 23: Event-Study Robustness for Switching into Big 4" class="figure-img" loading="lazy" src="tables/big4_effect_latex/22_eventstudy_robustness_full.png"/>
<figcaption>Table 23: Event-Study Robustness for Switching into Big 4</figcaption>
</figure>
</details>
<details>
<summary>
补充：收费、市值与其他质量指标
</summary>
<p>审计费用与公司市值</p>
<p>审计收费的变化比较明确：审计收费呈现极其清晰的价格溢价：换入四大后审计费用对数增加约 0.370（约高出 45%），换出后减少约 0.242。同时，换入后企业市值对数上升 0.104。</p>
<figure class="latex-table figure" id="latex-table-14">
<img alt="Table 14: Big 4 Auditors, Audit Fees, and Market Value" class="figure-img" loading="lazy" src="tables/big4_effect_latex/14_audit_fees_and_valuation_full.png"/>
<figcaption>Table 14: Big 4 Auditors, Audit Fees, and Market Value</figcaption>
</figure>
<p>本节进一步考察盈余质量、监管门槛操纵与失败严重程度等替代口径。</p>
<section class="level5" id="应计与真实盈余管理">
<h5 class="anchored" data-anchor-id="应计与真实盈余管理">6.1 应计与真实盈余管理</h5>
<p>换入四大后，Jones 异常应计与真实盈余管理未见系统性下降；Dechow-Dichev 异常应计绝对值反而略升 0.034（<span class="math inline">\(p=0.006\)</span>）。</p>
<figure class="latex-table figure" id="latex-table-13">
<img alt="Table 13: Big 4 Auditors and Earnings Quality" class="figure-img" loading="lazy" src="tables/big4_effect_latex/13_earnings_quality_full.png"/>
<figcaption>Table 13: Big 4 Auditors and Earnings Quality</figcaption>
</figure>
</section>
<section class="level5" id="roe-监管门槛检验">
<h5 class="anchored" data-anchor-id="roe-监管门槛检验">6.2 ROE 监管门槛检验</h5>
<p>在 0%、6% 和 10% 等配股与监管门槛附近，四大客户的聚集与盈余管理交互项未见一致的抑制模式。</p>
<figure class="latex-table figure" id="latex-table-15">
<img alt="Table 15: Big 4 Auditors and ROE Threshold Indicators" class="figure-img" loading="lazy" src="tables/big4_effect_latex/15_roe_threshold_bunching_full.png"/>
<figcaption>Table 15: Big 4 Auditors and ROE Threshold Indicators</figcaption>
</figure>
<figure class="latex-table figure" id="latex-table-16">
<img alt="Table 16: ROE Thresholds, Big 4 Auditors, and Earnings Management" class="figure-img" loading="lazy" src="tables/big4_effect_latex/16_roe_threshold_earnings_full.png"/>
<figcaption>Table 16: ROE Thresholds, Big 4 Auditors, and Earnings Management</figcaption>
</figure>
<figure class="latex-table figure" id="latex-table-17">
<img alt="Table 17: Big 4 Auditors and Components of Real Earnings Management" class="figure-img" loading="lazy" src="tables/big4_effect_latex/17_roe_threshold_rem_components_full_p01.png"/>
<figcaption>Table 17: Big 4 Auditors and Components of Real Earnings Management</figcaption>
</figure>
<figure class="latex-table figure" id="latex-table-18">
<img alt="Table 18: Big 4 Auditors and Inventory Impairment" class="figure-img" loading="lazy" src="tables/big4_effect_latex/17_roe_threshold_rem_components_full_p02.png"/>
<figcaption>Table 18: Big 4 Auditors and Inventory Impairment</figcaption>
</figure>
</section>
<section class="level5" id="失败严重程度与文本挖掘">
<h5 class="anchored" data-anchor-id="失败严重程度与文本挖掘">6.3 失败严重程度与文本挖掘</h5>
<p>严重违规的固定效应差异为 <span class="math inline">\(-1.78\)</span> 个百分点；换入四大的系数为 <span class="math inline">\(-1.66\)</span> 个百分点（10% 水平边缘显著）。严重程度的抑制证据主要局限于违规，在重述上未见显著改变。</p>
<figure class="latex-table figure" id="latex-table-4">
<img alt="Table 4: Big 4 Auditors and Indicators of Unwarned Failure Severity" class="figure-img" loading="lazy" src="tables/big4_effect_latex/04_failure_severity_indicators_full.png"/>
<figcaption>Table 4: Big 4 Auditors and Indicators of Unwarned Failure Severity</figcaption>
</figure>
<figure class="latex-table figure" id="latex-table-5">
<img alt="Table 5: Big 4 Auditors and Log Magnitudes of Unwarned Failures" class="figure-img" loading="lazy" src="tables/big4_effect_latex/05_failure_severity_magnitudes_full.png"/>
<figcaption>Table 5: Big 4 Auditors and Log Magnitudes of Unwarned Failures</figcaption>
</figure>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_effect_notebook/severity_distribution_1A.png" style="width:100.0%"/></p>
<figcaption>违规与重述事件严重程度数值分布</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img alt="违规和重述公告文本特征的命中次数，类别可以重叠" class="img-fluid figure-img" src="figures/big4_effect_notebook/text_mining_features_1B.png" style="width:100.0%"/></p>
<figcaption>违规与重述公告的文本特征命中次数</figcaption>
</figure>
</div>
</section>
<section class="level5" id="子样本换所-did">
<h5 class="anchored" data-anchor-id="子样本换所-did">6.4 子样本换所 DID</h5>
<p>在财务困境（当年亏损或 Z-score 偏低）与长期任期子样本中，换入四大的失败率系数部分为负，但伴随较宽的置信区间。</p>
<figure class="latex-table figure" id="latex-table-6">
<img alt="Table 6: Switching Big 4 Auditors and Unwarned Failures: Subsamples" class="figure-img" loading="lazy" src="tables/big4_effect_latex/06_failure_subsamples_full.png"/>
<figcaption>Table 6: Switching Big 4 Auditors and Unwarned Failures: Subsamples</figcaption>
</figure>
</section>
<section class="level5" id="其他质量指标的描述比较">
<h5 class="anchored" data-anchor-id="其他质量指标的描述比较">6.5 其他质量指标的描述比较</h5>
<p>在真实盈余管理分项、盈余平滑度与激进度、会计稳健性及隐含资本成本（ICC）等指标上，四大客户均未显现出单调占优的质量梯度。</p>
<p><img alt="真实盈余管理四项指标分组均值。" class="img-fluid" data-fig-cap="真实盈余管理：描述性均值对比。" src="figures/audit_quality_secondary/rem_overall_comparison.png" style="width:100.0%"/></p>
<p><img alt="盈余激进度和平滑度的分组均值。" class="img-fluid" data-fig-cap="盈余披露质量对比。" src="figures/audit_quality_secondary/ear_dis_overall_comparison.png" style="width:100.0%"/></p>
<p><img alt="会计稳健性年度指标分组均值。" class="img-fluid" data-fig-cap="会计稳健性指标对比。" src="figures/audit_quality_secondary/conservatism_overall_comparison.png" style="width:100.0%"/></p>
<p><img alt="按事务所类别分组的 PEG 隐含权益资本成本均值。" class="img-fluid" data-fig-cap="隐含权益资本成本对比。" src="figures/audit_quality_secondary/icc_overall_comparison.png" style="width:100.0%"/></p>
<p><span id="full-12_big4_effect-7"></span></p>
</section></details>
</section>
</section>
<section class="level2" id="市场是否区别对待财报信息">
<h2 class="anchored" data-anchor-id="市场是否区别对待财报信息">5. 市场消息反应：门槛、斜率与固定水平差</h2>
<p>盈余惊喜统一为实际EPS减分析师最新预测中位数，再除以预测中位数绝对值。以下三个问题不同：正向消息组相对中性组的路径差；连续surprise每增大一定幅度的斜率差；给定同一surprise时的条件收益水平差。对数股价系数和百分比CAR也不能混用。</p>
<section class="level3" id="连续消息的正式检验">
<h3 class="anchored" data-anchor-id="连续消息的正式检验">5.1 连续消息的正式检验</h3>
<p>连续消息与审计师身份的交互对应 Teoh 与 Wong（1993）的 ERC 比较形式；消息分母、窗口和控制不同，斜率与水平差分别解释。</p>
<p>连续线性与样条规格使用同一30,064个完整事件、330,646日观测，吸收公司×财年、事件日和交易日FE，按公司×财年聚类，不追加controls或缩尾。加入组别×事件日的低阶项。CAR为从−5日起累计市场调整日收益的100倍；各事件日估计相对−1日解释，表中已经是百分点，不再乘100。线性模型将surprise按0.10缩放，故slope10回答消息增加10个百分点的额外反应。</p>
<p>四大−Other的线性斜率在公告日为0.0084075个百分点（SE=0.003718，CI=[0.001120,0.015695]，p=0.02375），+1为0.0112325（SE=0.005484，p=0.04056），+5为0.000157（p=0.987）。在固定S=0.10处，线性总水平差公告日为0.186834（SE=0.069182，p=0.006925），+1为0.212563（p=0.01945），+5为0.242856（p=0.07762）。截距与斜率共同组成固定水平差，不能称其为ERC斜率。</p>
<p>样条固定S=0.10的四大水平差公告日0.343981（SE=0.109843，p=0.001740），+1为0.378394（p=0.01133），+5仍为0.559373（SE=0.221490，CI=[0.125242,0.993503]，p=0.01156）。所以不能笼统说“所有连续规格+5都不显著”。本土八大的线性斜率证据较弱，样条固定S公告日和+1水平差为正且显著；全表同时保留这些差异。</p>
<p>线性CAR四大前期斜率联合检验p=0.156、全时期斜率联合p=0.024；样条前期联合p=0.087、全时期p&lt;0.001。前期未达5%显著不是等价性证明；样条也提示10%层面的前期差异。这里记录条件反应关系，尚未识别聘用四大的因果认证效应。</p>
<figure class="latex-table figure">
<img alt="Continuous Earnings Surprise: Slopes and Fixed-Surprise Gaps" class="figure-img" loading="lazy" src="tables/big4_evidence/continuous_market_car.png" style="width:734px"/>
<figcaption>Continuous Earnings Surprise: Slopes and Fixed-Surprise Gaps</figcaption>
</figure>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_evidence/linear_slopes_car_pct.png" style="width:100.0%"/></p>
<figcaption>连续盈余惊喜：三类事务所的CAR反应斜率</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_evidence/spline_gaps_car_pct.png" style="width:100.0%"/></p>
<figcaption>给定盈余惊喜的CAR水平差：样条模型</figcaption>
</figure>
</div>
</section>
<section class="level3" id="门槛模型与消息可比性">
<h3 class="anchored" data-anchor-id="门槛模型与消息可比性">5.2 门槛模型与消息可比性</h3>
<p>原64门槛模型比较surprise&gt;10%与[−10%,10%]，将其余大负消息排除。原三组pooled规格没有单独的组别×事件日低阶项；其四大−Other公告日差0.003837（SE=0.001331，p=0.004）是未乘100的log价格单位。78完整二组交互把本土八大与Other合为Non-Big4，并补齐低阶项；在10%门槛下，log价格公告日差0.000903（SE=0.001458，p=0.536），CAR差0.093442个百分点（SE=0.146302，p=0.523）。两者改变了参照组及规格，不应互相替代。</p>
<p>要求预测DeclareDate严格在年报公告前，随后重新选择每机构最新合格预测，四大−Other公告日差仍为0.003606（SE=0.001338，p=0.007）。再按已确认四变量1%—99%共同区间筛选，公告日差0.002905（SE=0.001653，p=0.079），+1和+5不显著；共同样本加入既有81控制后公告日0.001510（SE=0.001671，p=0.366）。相应事件数20,336→20,221→16,115。变化同时包含比较对象和精度变化，不能作为selection份额。</p>
<p>共同支持样本无控制的本土八大−Other公告日0.002295（p=0.049），加controls后0.001990（p=0.088）；四大−本土八大仍不显著。筛后市值和覆盖并未完全平衡。连续74与这些门槛结果并列回答不同问题，不能用某个筛后不显著结果覆盖已经完成的正式连续正向检验。</p>
<figure class="latex-table figure">
<img alt="Big 4 Minus Other: Forecast Timing and Comparable Samples" class="figure-img" loading="lazy" src="tables/big4_evidence/comparable_market_response.png" style="width:734px"/>
<figcaption>Big 4 Minus Other: Forecast Timing and Comparable Samples</figcaption>
</figure>
<details>
<summary>
补充：原三组门槛扫描和完整支持
</summary>
<p>正向盈余惊喜与公告期股价反应</p>
<p>定义盈余惊喜为实际 EPS 超出分析师预测中位数的比例（<span class="math inline">\(Surprise &gt; 10\%\)</span>）。以公告前一交易日为基期，估计公告前后五个交易日的对数股价轨迹。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/erc/positive_response_panels_180d_threshold_0p1.png" style="width:100.0%"/></p>
<figcaption>正向盈余惊喜与公告期股价反应</figcaption>
</figure>
</div>
<p>门槛规格描述正向消息组的公告期路径，以下完整保留原图与门槛扫描，和连续消息规格分别解释。</p>
<p><strong>最新数据：门槛扫描与样本支持</strong></p>
<p>将正向消息门槛从 5% 逐点提高至 30%，每次比较 <span class="math inline">\(Surprise&gt;c\)</span> 与 <span class="math inline">\(-c\leq Surprise\leq c\)</span> 的事件。以下使用最新市场数据和原三组回归规格：2001—2024 财年、公告前 180 天预测、公司×财年、事件日及交易日期固定效应，公司×财年聚类，无额外控制变量。纵轴为四大或本土八大相对 Other 的正向消息反应增量，分别相对于公告前第 −1 个交易日；因变量为未乘以 100 的对数股价。</p>
<div class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-cap="左轴：正向消息反应相对 Other 的增量，阴影为 95% 点态置信区间。右轴：各门槛下四大、本土八大实际 pooled 样本中的正向事件／（正向＋中性事件）比例，浅色柱分别对应两组。柱高是样本支持比例，非 surprise 密度。横轴为固定 surprise 比率门槛，非样本分位数；竖线标示 10%。各门槛保留全部估计，并不构成对最优经济门槛的识别。" id="fig-original-threegroup-threshold-scan">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-original-threegroup-threshold-scan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img class="img-fluid figure-img" data-fig-cap="左轴：正向消息反应相对 Other 的增量，阴影为 95% 点态置信区间。右轴：各门槛下四大、本土八大实际 pooled 样本中的正向事件／（正向＋中性事件）比例，浅色柱分别对应两组。柱高是样本支持比例，非 surprise 密度。横轴为固定 surprise 比率门槛，非样本分位数；竖线标示 10%。各门槛保留全部估计，并不构成对最优经济门槛的识别。" src="figures/market_information/event_study/threshold_scan_original_threegroup/pooled_gap_threshold_scan_with_support.png" style="width:100.0%"/>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-original-threegroup-threshold-scan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">图 3: 原三组模型的正向消息门槛扫描与样本支持</figcaption>
</figure>
</div>
<p>10% 点与原三组图的系数、标准误、置信区间及样本量完全一致：四大−Other 在第 0 天为 0.003837（标准误 0.001331，<span class="math inline">\(p=0.004\)</span>），第 +1 天为 0.003671（标准误 0.001790，<span class="math inline">\(p=0.040\)</span>），第 +5 天为 0.003066（标准误 0.002672，<span class="math inline">\(p=0.251\)</span>）。完整扫描中，第 0 天的四大增量在 5%—18% 门槛达到 5% 显著性，第 +1 天在 10%—15% 达到；第 +2、+5 天均未达到 5% 显著性。</p>
<p><strong>曲线右端为何下降？</strong> 提高门槛同时改变了正向组和中性组，因而每个点对应不同的组间比较。四大正向事件从 10% 门槛的 817 个降至 30% 的 334 个，正向组占该组实际正向＋中性样本的比例从 31.7% 降至 11.3%；高门槛仍有正向事件，不能解释为“没有 treatment”。正向支持减少与估计精度下降相伴，但并不机械地使系数趋近于零。</p>
<p>右端下降也不是只有置信区间变宽：将门槛从 15% 提高到 18%，第 +1 天四大−Other 的点估计从 0.004331 降至 0.002457，而标准误只从 0.002041 升至 0.002164。在同一 pooled 模型中拆开看，四大组内正向消息反应从 0.004949 降至 0.003692，Other 从 0.000618 升至 0.001235，两者共同缩小了差值。同期正向组减少，原来属于正向组的中等正向消息进入中性组，且中性组也纳入更负的消息；组别构成和两组的反应差异随之改变。这些变化是需要区分的解释，目前尚未通过固定样本或逐项分解确定哪个因素主导下降。</p>
<p><strong>理论上为什么可以下降？</strong> 门槛扫描改变比较组，不是沿着同一公司的消息反应函数移动。若四大的反应优势集中在中等消息，而大消息下两组反应逐渐趋同，提高门槛会更多保留组间差异较小的尾部消息。允许各组有自身中性路径时，将已有正向反应的中等消息纳入中性组也可能缩小正向对中性的差值；但原模型省略了组别×事件日项，不能直接用两组各自“正向减中性”的解释替代其系数。</p>
<p>一个简化反例可以说明这点，但不代表本数据的拟合：设两组 surprise 均匀分布于 0 至 1，四大反应为 <span class="math inline">\(r_4(s)=A\min(s/0.10,1)\)</span>，Other 为 <span class="math inline">\(r_O(s)=A\min(s/0.30,1)\)</span>，<span class="math inline">\(A&gt;0\)</span>。四大在中等消息时反应更高，但两组最终达到相同平台。忽略日期固定效应的简化 pooled 模型中，共同中性基准在组间相减时抵消；当 <span class="math inline">\(0.10\leq c\leq0.30\)</span> 时，正向组平均反应差为 <span class="math inline">\(A(0.30-c)^2/[0.60(1-c)]\)</span>，随门槛下降至零。这里没有抽样误差，正向样本也没有消失，下降来自尾部消息的反应差异。相反，在共同分布、线性反应及固定四大斜率优势的简单设定下，不能仅靠提高门槛解释下降。该例只说明下降在理论上可能，实际模型还包括日期固定效应；当前结果仍需区分反应非线性、样本构成和 EPS 比率分母造成的大 surprise，尚未确认是哪种机制。</p>
<p>解释还受到原规格及前期路径限制：原 pooled 模型未单独加入事务所组别×事件日项；四大−Other 的公告前 −5 至 −2 日联合检验，在 9% 及 11%—27% 门槛达到 5% 显著性，10% 门槛的 <span class="math inline">\(p=0.063\)</span>。因此，这张图支持原规格下的公告初期条件差异，尚不能单独将其归因为纯信息认证，也不能用不同门槛下显著性变化证明效应消失。</p>
</details>
<details>
<summary>
补充：原二组门槛图
</summary>
<p>原二组图保留作设计比较；它不替代上文完整二组交互及连续模型的正式检验。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/erc/2grps_ln_p_pos_thresh_0p1_FE1.png" style="width:100.0%"/></p>
<figcaption>原二组正向消息路径</figcaption>
</figure>
</div>
</details>
</section>
<section class="level3" id="年度car曲线的展示对象">
<h3 class="anchored" data-anchor-id="年度car曲线的展示对象">5.3 年度CAR曲线的展示对象</h3>
<p>年度四窗口CAR图使用29,397公司年度、4,181公司、24财年，吸收公司和财年FE，按公司×财年聚类，纵轴为小数收益而非百分点。它是一行一事件的四个窗口收益曲线；74则是一行一日、含公司×财年及交易日FE的累计CAR路径，两者不能用图形高低直接替代正式斜率或固定S差异检验。图中95%区间为点区间，不是整条曲线的联合检验。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img class="img-fluid figure-img" src="figures/big4_evidence/annual_car_curves.png" style="width:100.0%"/></p>
<figcaption>盈余惊喜与四个公告窗口的年度CAR关系</figcaption>
</figure>
</div>
</section>
</section>
<section class="level2" id="当前解释与待完成">
<h2 class="anchored" data-anchor-id="当前解释与待完成">6. 当前解释与待完成</h2>
<p>现有基础设计得到三项具体认识。第一，四大进入者已有可观察的客户差异，年度匹配后失败差异仍为负；但剩余差异不等于审计师私有信息。第二，中间口径换所及九项匹配DID给出较稳定的负向结果，严格口径和部分动态结果更敏感；审计处理效应不能被统一否定，也尚不能推广到所有客户和质量维度。第三，部分连续市场规格支持公告初期斜率差及固定消息水平差，门槛与筛选结果则显示规格和参照组的重要性。</p>
<p>这些结果与审计服务、客户选择和信息可信度同时有关，目前没有完成三者的数值分解。尤其是研究者未测到的特征未必对投资者未知；进入前第1财年的192份已知审计报告均在进入财年出具，尚未对齐实际聘任与公开信息时点。不能由换所不显著推导“全部优势来自selection”，也不能由价格反应与收费溢价推导“收费本质就是认证费”。</p>
<p>下一步集中于基础比较中已明确的剩余工作：确认34五项controls用于选择方程还是也精简结果方程；保留九项完整结果作为对照；核对共同支持和残余尾部不平衡的解释；在同一估计对象内检验消息与客户可比性。未来盈利／现金流兑现以及人员、分所覆盖放在补充研究位置，不作为当前机制已经成立的证据，也不在本次新增估计。</p>
<details>
<summary>
数据、方法及完整估计材料
</summary>
<p><strong>估计程序归档。</strong> 00_big4_effect_inputs.do · 00_big4_effect_did_models.do · 26_client_selection_opinion_mechanism.do · 63_earnings_response_horizons.do</p>
</details>
</section>
</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "已复制");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "已复制");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
</body></html>